### ISSUE TITLE
Chart does not render properly inside of an html table

### ISSUE THREAD

**Issue by skcord** [masayuki0812/c3#1000]
Hello:

The chart does not render properly, when placed inside of an html table.  Is this a known issue, or is my usage off?

Thank you.

* d3 version 3.5.5
* c3 version 0.4.9
* Firefox 31.4.0 ESR
* Chrome 40.0.2214.111 m

```
<table style="width: auto;">
    <tr>
        <td style="vertical-align: top;">
	      <div id="infrastructureChart"></div>
	    </td>
    </tr>
</table>
```
 ```
var infraChart = c3.generate({
				bindto: '#infrastructureChart',
				data: {
				  columns: [
					['Infrastructure', 24610,81401,164696,263135,391863,567917]
				  ],
				  types: {
					Infrastructure: 'bar'
				  }
				},
				axis: {
				  y: {
					label: {
					  text: 'Y Label',
					  position: 'outer-middle'
					},
					tick: {
					  format: d3.format("$,")
					}
				  }
				}
			});
```
Screenshot inside of the table:
![insideoftable](https://cloud.githubusercontent.com/assets/7861168/6192347/babf4f6e-b365-11e4-8cc6-d20cedbf0047.png)

Screenshot outside of the table:
![outsideoftable](https://cloud.githubusercontent.com/assets/7861168/6192364/ee2080c6-b365-11e4-8d82-642aae628903.png)

**Comment by masayuki0812** [comment]
These GitHub issues are for bug reports and feature requests only, so please use Google Group https://groups.google.com/forum/#!forum/c3js for help at the moment.
