### ISSUE TITLE
How to show some sort of loading screen until the full chart gets displayed?

### ISSUE THREAD

**Issue by sanke93** [masayuki0812/c3#1001]
When dealing with lot of points on timeseries, it takes a bit of time for the graph to be fully loaded. So even if I hide the loading screen after c3.generate() is called, I still see that the graph hasn't been fully drawn yet so the loading screen isn't that helpful in that case. Is there some kind of callback or a variable that tracks if the chart has been fully drawn out? Since this is a question, please add the question label to it, can't seem to be able to do it myself. Thanks!

**Comment by aendrew** [comment]
@sanke93 Could you please ask this in the C3 Google Group instead? Thanks! https://groups.google.com/forum/#!forum/c3js

**Comment by sanke93** [comment]
yup sorry about that!

**Comment by aendrew** [comment]
@sanke93 No worries! :smile:
