### ISSUE TITLE
Grid lines don't appear if transition duration set to 0

### ISSUE THREAD

**Issue by ikreymer** [masayuki0812/c3#1002]
This seems to be a bug and was hard to track down, so I thought I'd report it in case others run into this.

To repro, go to http://c3js.org/samples/grid_x_lines.html and add

```
    transition: {
        duration: 0,
    },
```

The x lines will disappear. An easy workaround is to set the duration to 1, but this seems to be unexpected behavior.

**Comment by danelkhen** [comment]
Just found that out too, so, +1 for me... :-)

**Comment by vanjar** [comment]
Regions don't appear also.

**Comment by masayuki0812** [comment]
Thanks for reporting. Is this still happening in `0.4.10-rc4`? I cannot see this issue and it seems fixed already in this version.

**Comment by masayuki0812** [comment]
`0.4.10` has been released, so let me close at the moment. Thanks.
