### ISSUE TITLE
Simple Typo

### ISSUE THREAD

**Issue by GordonSmith** [masayuki0812/c3#1007]
https://github.com/masayuki0812/c3/blob/master/c3.js#L720

Says 'categor' and should be 'category'

**Comment by aendrew** [comment]
@GordonSmith Hi! Good spot! 

Want to do an easy Pull Request? Go [here](https://github.com/masayuki0812/c3/edit/master/c3.js#L720), save and follow the directions. Make sure to put "Fixes #1007" in the commit message! :smile:
