### ISSUE TITLE
Multiple pie chart legend label width

### ISSUE THREAD

**Issue by rhenna** [masayuki0812/c3#1011]
An example of the issue is here: http://jsfiddle.net/2rfpnnso/

It appears that the width of a legend label for the pie chart is calculated only once per data key. Subsequent charts on the same page that share keys will use the previously calculated label width. In the link above, the second pie chart uses keys from the data in the first pie chart, causing its longer labels to overlap. In the third pie chart, the first series has a much shorter label than the space allocated for it.

**Comment by kdekooter** [comment]
:+1: having similar issues. We should be able to give legend labels a fixed size, preferably using CSS.

**Comment by masayuki0812** [comment]
Thanks for reporting. It's a bug and I think it's been fixed in the commit above. I'll release this fix in the next version `0.4.10` shortly. Thanks!

**Comment by masayuki0812** [comment]
`0.4.10` has been released, so let me close. Thanks!
