### ISSUE TITLE
X-axis label incorrect position and rotation after flow

### ISSUE THREAD

**Issue by rhenna** [masayuki0812/c3#1012]
Here's an example: http://jsfiddle.net/hne3p19k/

If flow is called on a chart with rotated x-axis labels, the labels end up in the wrong position after the flow is done animating. Additionally, if tick fit is false, the newly added data point x-axis label is not rotated until another flow() call is made and another data point is added to the chart.

**Comment by masayuki0812** [comment]
Thanks for reporting. I think this has been fixed by the commit above, and I'll release this fix in the next version 0.4.10 shortly. Thanks!

**Comment by masayuki0812** [comment]
`0.4.10` has been released, so let me close at the moment. Thanks.
