### ISSUE TITLE
Load with colors

### ISSUE THREAD

**Issue by SegFaultx64** [masayuki0812/c3#1017]
Right now there is no way to load new data with colors. The it seems like it would be a simple fix along the lines of how axes work in the load api to hook this up. I am not sure if there is another option for this but I could not get one to work.

**Comment by SegFaultx64** [comment]
Just wanted to follow up and see if there was any action on getting that pull request merged?

**Comment by masayuki0812** [comment]
I merged the PR. Thanks!!

**Comment by masayuki0812** [comment]
`0.4.10` has been released, so let me close. Thanks!
