### ISSUE TITLE
How to add error bar chart in to C3JS ?

### ISSUE THREAD

**Issue by mistrynilesh440** [masayuki0812/c3#1022]
I have three types of values available(higher,medium and lower). Can you please help out how to add this chart in to existing architecture ? Thanks in advance.

![images](https://cloud.githubusercontent.com/assets/11177229/6351140/10880cf4-bc5f-11e4-9e0b-36a3f7895c6d.jpg)

**Comment by masayuki0812** [comment]
This is a duplicate of #253 , so let me close.
