### ISSUE TITLE
c3 chart not loading.

### ISSUE THREAD

**Issue by PrashantMangale** [masayuki0812/c3#1027]
Hey, I'm new to c3js. I tried some examples of c3js. And i got success in that. But i have one problem when i trying to load graph first time in any browser, it doesn't show me graph. And if i reload page once or twice it shows graph. 
I'm using this library in my project, so i want to load all graphs on HTML page when page load first time.
I want solution on it, Please give me some feedback because i want to use in my project.

**Comment by ergo** [comment]
Please provide us with some test code so someone can replicate your issue - but it looks like you might be running into some race conditions.

**Comment by PrashantMangale** [comment]
Can u explain in detail? What you want to say?

Actually i'm reading json file and that providing json file data to line chart or bar chart. Data is coming and also getting to chart. But prob is graph not loading when page load first time,

**Comment by ergo** [comment]
I'm trying to say we won't be able to help you if you can't provide a link to application that experiences the problem or create some kind of plunker/jsfiddle demo that demonstrates it.
Your description is not enough to help you.

Check your debug console on load to see possible exceptions.

**Comment by aendrew** [comment]
Mind trying it with C3 4.10-rc1? My PR at #938 may fix this.

**Comment by masayuki0812** [comment]
As I wrote #1027 , can you try `0.4.10-rc4`? This version includes the fix.

**Comment by PrashantMangale** [comment]
ok.i will try. And thanks for your help. If i need any help, i'll definately call you.
