### ISSUE TITLE
How can I change tooltip structure ?

### ISSUE THREAD

**Issue by mistrynilesh440** [masayuki0812/c3#1037]
is there any way to change tooltip structure ?
I have multiple lines in single chart it shows long list on mouse hover.
If I have 16 lines then it creates 16 rows for tooltip.

**Comment by EABCenter** [comment]
Yes, you can use the tooltip.content setting to override the tooltip and completely customize it so that it will look any way you want.
http://c3js.org/reference.html#tooltip-contents

**Comment by mistrynilesh440** [comment]
Thank You!
