### ISSUE TITLE
TypeError: c is undefined c3.min.js:4

### ISSUE THREAD

**Issue by jackRogers** [masayuki0812/c3#1042]
Failing to get a basic example working.  Downloaded and setup everything as instructed.

/var/www/html/c3-0.4.9 $ ls
bower.json  c3.min.css      d3.js      extensions        LICENSE       spec
c3.css      c3.min.js       d3.min.js  Gruntfile.coffee  package.json  src
c3.js       component.json  d3.zip     htdocs            README.md

put my test file in /var/www/html
page is blank.  Inspector console says there is an error in c3.min.js
TypeError: c is undefined c3.min.js:4

screenshot of script attached
![untitled](https://cloud.githubusercontent.com/assets/1609589/6471471/47646ede-c1b9-11e4-9a6b-4c8192070e0b.png)

**Comment by lilasquared** [comment]
Looks to me like the script might be executing before the page is rendered.  What happens if you put the script tag containing the generate function after the div, inside the body of the document?

**Comment by aendrew** [comment]
@jackRogers +1 for @lilasquared's suggestion. It's generally better to put JavaScript in the footer to prevent scripts blocking the rest of the page, but it's especially necessary with C3 as the generation code needs to be after the referenced element.

I'm pretty confident doing so will fix your issue so closing; if you're still having problems, let me know and I'll reopen. Thanks!

**Comment by jackRogers** [comment]
same result
![screenshot-10](https://cloud.githubusercontent.com/assets/1609589/6490335/755dc406-c273-11e4-832d-3a54f5992d56.png)

**Comment by jackRogers** [comment]
additionally, when I use c3.js instead of c3.min.js, i get a differnt error
TypeError: d3 is undefined c3.js:5446

**Comment by aendrew** [comment]
That means D3 isn't loaded before C3 calls it. Are you loading dependencies in this order?

D3
C3
<your invocation code>

**Comment by jackRogers** [comment]
You can see in the code in the attached screenshots.  I also tried loading d3 before the c3.css but that did not affect either error.

**Comment by jackRogers** [comment]
Resolved issues.  d3 script line was incorrect.  c3 is great.  My apologies.

**Comment by aendrew** [comment]
:+1: Glad to hear you figured it out. In the future, mind submitting support requests to the [Google Group](https://groups.google.com/forum/#!forum/c3js)? We're trying to keep the issue queue specifically for bug reports. Thanks!
