### ISSUE TITLE
Legend overlapping when I add multiple charts

### ISSUE THREAD

**Issue by martin-linha** [masayuki0812/c3#1051]
Hi,

I am having a problem with legend overlapping. It occurs when I add multiple charts on the same page. See:

http://jsfiddle.net/martinlinha/azo35o4u/

Any ideas?

Thanks!
Martin

**Comment by octant** [comment]
Hi @martin-linha,

After playing with the example a bit, it looks like the second pie chart takes on the spacing of the pie chart that was defined first. I don't know how to fix this issue or if there's something subtle we're missing, but as a work around until this is fixed you can move the legend to the [left or right](http://jsfiddle.net/azo35o4u/4/).

**Comment by octant** [comment]
Actually, it looks like [this has been fixed](https://github.com/masayuki0812/c3/issues/1011).

**Comment by masayuki0812** [comment]
Yeah, this issue has been fixed in #1011 , so let me close this issue as well. Thanks.
