### ISSUE TITLE
Pie, Donut & Gauge Chart Hide Serie on Click

### ISSUE THREAD

**Issue by GermainBergeron** [masayuki0812/c3#1052]
An error is thrown when hidding a serie with the "onclick" event on pie, donut and gauge charts. See http://jsfiddle.net/3x78m8sf/ . 

I used the logic of c3's legend onclick
```
onclick: function(d, i) {
    chart.toggle(d.id);
    chart.revert();            
}
```

The error is not thrown on other chart type

**Comment by masayuki0812** [comment]
I pushed your fix, so let me close. Thanks.
