### ISSUE TITLE
Data labels do not shift in concert with associated bars in bar chart.

### ISSUE THREAD

**Issue by EABCenter** [masayuki0812/c3#1055]
I was able to recreate this issue in the latest version of Chrome, on OSX 10.9.5, using the examples from the website, as well as my own code base.

Steps to reproduce:
Render a bar chart with multiple bars that is responsive to the width of the window.  Be sure to include the data label.
You should see a bar chart with numbers at the top of each of the bars.
Expand and/or contract the window.
You should see the bars, x-axis, grid, and other elements stretch, or shrink, to match the window size.  The data labels, however, do not shift from the positions in which they were initially rendered.
OR
Visit http://c3js.org/samples/data_label.html and resize the window for the same results.

**Comment by prschulz** [comment]
I am also experiencing this issue and am searching for a fix - @EABCenter any luck on finding a workaround?

**Comment by EABCenter** [comment]
@prschulz, FYI it seems to have been corrected in the latest release.
