### ISSUE TITLE
Question: How to change value of percentage in donut chart with text

### ISSUE THREAD

**Issue by dannymaulana234** [masayuki0812/c3#1081]
is there any way to show value in donut chart with text ?
I have this code :
columns: [
            ["Tablet", 30],
            ["Smartphone", 25],
            ["Others", 24],
            ["Desktop", 50],
          ]

e.g. I want to show Tablet instead percentage.
I appreciate your help . thanks in advance

**Comment by aendrew** [comment]
@dannymaulana234 

```

var chart = c3.generate({
    data: {
        // iris data from R
        columns: [
            ['data1', 30],
            ['data2', 120],
        ],
        type : 'pie',
    },
    pie: {
        label: {
            format: function(d, v, i) {
                return i;
            }
        }
    } 
});
```
See [pie.label.format](http://c3js.org/reference.html#pie-label-format)

Please ask such questions in the future to the [Google Group](https://groups.google.com/forum/#!forum/c3js); we're trying to keep the issue queue specific to bugs. Thanks!

**Comment by justindchan** [comment]
its so easy, thank you!
