### ISSUE TITLE
Donut chart data is displaying incorrectly

### ISSUE THREAD

**Issue by rubsav** [masayuki0812/c3#1101]
It should display 100% with single color.

![image](https://cloud.githubusercontent.com/assets/9221980/6967722/1bf386b2-d92f-11e4-90a5-f20fdca8e777.png)

![image](https://cloud.githubusercontent.com/assets/9221980/6967730/26afecd0-d92f-11e4-9c08-be0dcda605ac.png)

**Comment by fredpyo** [comment]
I'm just another c3js user, but I think it'll be better for the maintainers of c3js if you could provide some additional data an how to replicate to your issue. Perhaps a short [jsfiddle](https://jsfiddle.net/) that replicates your issue?
