### ISSUE TITLE
change D3 to peerDependencies.

### ISSUE THREAD

**Issue by gilbarbara** [masayuki0812/c3#1106]
I'm using c3 in a project where I also need to have d3 installed with the latest version (3.5.5).
But using browserify to bundle my app, c3 carries its own copy of d3 (<= 3.5.0) meaning duplicate code..

cheers

**Comment by aendrew** [comment]
This isn't a bad idea at all; I use C3 in lots of projects where I also use D3. :+1:

**Comment by ustccjw** [comment]
+1, and d3 version <= 3.5.0 depend `jsdom`(which depend `contextify`), but  `contextify` can not work well in iojs 3.0 (see https://github.com/brianmcd/contextify/issues/173)

**Comment by aendrew** [comment]
Worth seeing the discussion in #1166 re: peerDependencies (They don't work like you think they should in newer versions of NPM, so therefore we probably won't use them as such). 

Closing as a duplicate, please see #1062.
