### ISSUE TITLE
Suggestion: Tooltip position - left on right side chart and right on left side chart

### ISSUE THREAD

**Issue by Bear4** [masayuki0812/c3#1107]
With a large data series, (thick x-axis, 180 points * 18 series) tooltips hides data on the right edge of the chart.
Is it possible option where the tooltip after half the width of the chart - on the right half - goes to the left and on the left half of passes on the right. It would be nice to have that opportunity, I think so.
And I want to thanks for that great library. Very good job. Gratulations!
Images from issue:
![tooltip_on_right](https://cloud.githubusercontent.com/assets/8928341/7039959/afdfbeac-ddc8-11e4-8c25-1b94847c321d.jpg)

**Comment by lpkant** [comment]
hey,
actually something like this was introduced in 0.4.9 (#833) - it is a callback function for handling/overriding the tooltip position.
so you have to do the calculation on your own, but at least you should get what you want.

here are some inspirations:
* the original sample in #833
* below is a even more simplified version of showing a tooltip "above":

```javascript
  tooltip: {
	position: function(data, width, height, thisElement) {
	  var containerWidth, tooltipWidth, x, y;
	  containerWidth = element.clientWidth;
	  tooltipWidth = element.querySelector('.c3-tooltip-container').clientWidth;
	  x = parseInt(thisElement.getAttribute('x'));
	  if (x + tooltipWidth > containerWidth) {
		x = containerWidth - tooltipWidth - 2;
	  }
	  y = thisElement.getAttribute('y');
	  y = y - height;
	  return {
		top: y,
		left: x
	  };
	}
  }
```

hope it helps somehow!

**Comment by Bear4** [comment]
Thank You for replay. I set up my tooltip. 
I have one question what it's 'element' in Your code?
In my code I change element to document. And 'containerWidth' has no value (undefined) but 'tooltipWidth' has. 
So I must change (x + tooltipWidth > containerWidth) to (x > 550) where 550 is half width of my chart.
Anyway thanks a lot!

**Comment by lpkant** [comment]
sry, for confusing you - "element" originates from a knockout binding (in my source code), but it's just a DOM element - in this case the actual chart.

you might try adding "element":
```javascript
      ...
      var containerWidth, element, tooltipWidth, x, y;
      element = document.getElementById("yourChartId");
      containerWidth = element.clientWidth;
      tooltipWidth = ...
      ...
```

I am sure you'll now get a value for "containerWidth" -> so you eventually can use "containerWidth / 2" instead of hardcoded "550" that may fail if you have a responsive/resizing chart or environment.

**Comment by Bear4** [comment]
Thanks again for the clarification of the term an 'element'.
Now everything it's ok.

**Comment by gcobza2010** [comment]
Hi 

I need help on how to create a ultrachart  using open edge, a sample example will be appreciated. Thanks
