### ISSUE TITLE
duplicated id in group causes chart max y value to double

### ISSUE THREAD

**Issue by acamari** [masayuki0812/c3#1117]
I'm not sure if this qualifies has bug or "you shouldn't do that":

duplicated id in group causes chart max y value to double for each duplicated id - shrinking everything awfully.

I can reproduce this by typing this on: http://c3js.org/samples/timeseries.html

    var chart = c3.generate({
    data: {
        type: 'bar',
        x: 'x',
        rows: []
    },
    axis: {
        x: {
            type: 'timeseries',
            tick: {
                format: '%Y-%m-%d'
            }
        }
    }
    });

    chart.load({
        rows: [
                ['x','data1'],
                ['2013-01-01', 30],
                ['2013-01-02', 200]
        ]
    });
    //max y: 200    
    chart.groups([['data1','data1']]);//max y: 400
    chart.groups([['data1','data1']]);// y 400
    chart.groups([['data1','data1','data1']]);//y 800
    chart.groups([['data1','data1','data1']]);//y 800
    chart.groups([['data1','data1','data1','data1']]);//y 1600
    //chart.groups([['data1','data1','data1']]);//y 800

![datax1](https://cloud.githubusercontent.com/assets/716556/7156788/202f74e8-e32f-11e4-8e6f-94dd6ffd533a.png)
![datax2](https://cloud.githubusercontent.com/assets/716556/7156789/2030d860-e32f-11e4-9bd5-2515323da37f.png)
![datax3](https://cloud.githubusercontent.com/assets/716556/7156787/202ee0f0-e32f-11e4-824f-54585be170de.png)

**Comment by acamari** [comment]
ping

**Comment by aendrew** [comment]
I'm going to file this under "you shouldn't do that", not exactly sure how one would go about fixing that... If you can think of an edge case where fixing this would be beneficial, let me know and I'll reopen. Thanks!

**Comment by acamari** [comment]
I'm not sure either... Thanks!
