### ISSUE TITLE
Only integers on Y axis

### ISSUE THREAD

**Issue by alfredopacino** [masayuki0812/c3#1135]
Hi, the Y range is just 0-5: so the graph renders automatically 2 things I don't need:
- fractionals values: 1.5, 2.5
- a negative -0.5 value

How can avoid those both?

**Comment by ayozebarrera** [comment]
I solved my problem of fractionals values with

```javascript
tick: {
	format: function(d) {
		return d3.round(d); //this wil round the number (1.5 will be rounded to 1)
	}
}
```

But you should try to use the format function `d3.format("d")` 
More info [here](https://github.com/mbostock/d3/wiki/Formatting) in the d3 formatting documentation

Greetings

**Comment by alfredopacino** [comment]
it works indeed with
		```	tick: {
			format: d3.format("d")
			} ```

thanks

**Comment by xparthx** [comment]
yes, it works but it still shows the ticks for those floating values. So I think this option only hides label for the floating values:

![screenshot from 2017-08-01 12 04 32](https://user-images.githubusercontent.com/4241851/28812286-a3782d32-76b1-11e7-9954-d9937b4615e8.png)

How can I stop generating it? i.e not just hiding labels.

Here is the complete code which I'm using:

```
c3.generate({
    bindto: '#user-reg-linechart',
    data: {
        x: 'x',
        columns: [
            registrationDates,
            registrationCount
        ]
    },
    axis: {
        x: {
            type: 'timeseries',
            tick: {
                format: '%Y-%m-%d'
            }
        },
        y: {
            min: 0,
            tick: {
                format: d3.format('d')
            },
            padding: {top: 0, bottom: 0}
        }
    }
});
```

**Comment by Yaminn** [comment]
@ParthVora777 Did you find your solution?

**Comment by netooran** [comment]
I'm facing the same issue as @ParthVora777 pointed out. Does anyone have a solution?

**Comment by adong** [comment]
```
        tick: {
          // format: d3.format('d')
          format: function(d) {
            if (Math.floor(d) != d){
              return;
            }
            return d;
          }
        },
```
This turns my chart Y axis looks like:

![image](https://user-images.githubusercontent.com/15989893/98668581-ed1eeb80-2304-11eb-93c0-e471e408fc93.png)


Ref: [https://stackoverflow.com/questions/12643591/how-to-limit-d3-svg-axis-to-integer-labels](https://stackoverflow.com/a/12643613)
