### ISSUE TITLE
Optional Y key?

### ISSUE THREAD

**Issue by bwarren2** [masayuki0812/c3#1175]
I would like to be able to specify the value of y data members in scatterplots.
    
    // dataset = [
    //     {'x_var': 1, 'y_var': 1}
    //     {'x_var': 2, 'y_var': 3}
    //     {'x_var': 3, 'y_var': 4}
    // ]
     
    c3.generate({
        bindto: '#c3chart',
        data: {
          json: dataset,
          x: 'x_var'
          y: 'y_var'
          type: 'scatter',
        }
        }
    });

Is this something the maintainers want?  Whereabouts should I be working to add this?

**Comment by lmaccherone** [comment]
You can do that now using the `keys.value` configuration except keep in mind that you can multiple y-values so you have to specify it as an array with only one value in single y-values cases like your example. Here is an [example](http://c3js.org/samples/data_json.html). I've never tried it with a scatter chart but here is how I think it's supposed to work.

    c3.generate({
        bindto: '#c3chart',
        data: {
            json: dataset,
            keys:{
                x: 'x_var',
                value: ['y_var']
            },
            type: 'scatter'
        }
    });

**Comment by bwarren2** [comment]
Works perfectly.  Thanks for the heads up!
