### ISSUE TITLE
Browserify and C3

### ISSUE THREAD

**Issue by vinimxit** [masayuki0812/c3#1181]
How do i use C3 with Browserify and Backbone?

  d3 = require('d3'),
  c3 = require('c3'),

i am including my modules as above it shows the module doesn't exist though i have it in my node_modules.

**Comment by aendrew** [comment]
D3 is a dependency of C3. You don't need to require it separately. It's in c3's `node_modules` folder.

**Comment by ceremcem** [comment]
...however, you need to separately add `.css` files into your css bundle.
