### ISSUE TITLE
Why Y2 Axis starts adding padding always ?

### ISSUE THREAD

**Issue by abhi001** [masayuki0812/c3#1184]
Hi,

I am using latest c3.js for rendering stacked bar dual axis chart. 
I have used following property to show manipulated y1 and y2 axis tick values
*******************************
y: {
	                show: true,
	                tick: {
	                	 values: yAxisGridLinesArray.length > 0 ? yAxisGridLinesArray : undefined
                    }
	            },
	            y2: {
	            	show: isDualAxisValue ? true : false,
            		min: minY2AxisValue ? Number(minY2AxisValue) : undefined,
	            	max: maxY2AxisValue ? Number(maxY2AxisValue) : undefined,
	            	tick: {
	            		values: y2AxisGridLinesArray.length > 0 ? y2AxisGridLinesArray : undefined
	            	}
	            }
*******************************
![t2](https://cloud.githubusercontent.com/assets/4137391/7837874/67958496-04a7-11e5-998c-ec45cb19fb16.png)

As per the screenshot, Black line is showing start value for Y1 axis while Red line is showing start value for Y2 axis.
e.g. 0 on Y2 axis is parallel to the 55 on Y1 axis. 0 value on y2 axis should always start as same as y1 axis but it's not.

Is it possible to have the option to start Y2 axis from the bottom ? 
Can you please help whether we could modify c3.js to achieve as desired ?
Any help would be appreciated.
Cheers !

**Comment by thelastelf** [comment]
You can try to specify y2 min at 5, so on scale you will see 0
```
axis: {
        y2: {
            min:5,
           ...
}
```

**Comment by abhi001** [comment]
I tried following code and its working.

y: {
	show: true,
	padding: {top: 0, bottom: 0}
},
y2: {
	show: isDualAxisValue ? true : false,
	min: 0,
	padding: {top: 0, bottom: 0}
}
