### ISSUE TITLE
Clip path rect receiving no height/width (Chart appears blank)

### ISSUE THREAD

**Issue by impatient** [masayuki0812/c3#1189]
We're using c3 in an angular app, however when we draw the sample donut chart, it simply shows white space.  The root causes was that the defs + rects don't have a proper width/height associated with them.

![image](https://cloud.githubusercontent.com/assets/3408099/7914550/4c18e534-083d-11e5-8b7f-e2bb1e98f69f.png)

This is an odd situation. This works in most environments and the test case that I've created actually passes with the current code.

When determining size, it looks like the d3 select all doesn't do DOM traversal, so I wouldn't expect it to work with just id's as an array as written.

**Comment by jeremy-walsh-vgh** [comment]
seeing the same issue from a chart embedded on a visualforce page in salesforce.  rect has no height/width attributes.  Strange thing for me is that the page I'm debugging was working for a some time and then stopped; don't know what changed to stop it from rendering, but if I delete the clip path node from the defs in the chrome inspector, the chart renders correctly.

**Comment by NemSavic** [comment]
@jeremy-walsh-vgh if you're working with Visualforce pages in Salesforce it looks like this became an issue as of the Salesforce Winter 16 release. When you use apex:form tags or have showHeader="true" set in the apex:pages tag, Salesforce will load their own JS files which are now likely conflicting with something in C3.js

**Comment by impatient** [comment]
@jeremy-walsh-vgh I'd forgotten about this.  We ended up switching to D3 and the issue only recently popped up again.  I bet the updated Visualforce pages include Sizzle.. globally, which causes D3  to go down this path.

https://github.com/mbostock/d3/blob/master/src/selection/selection.js#L24

I bet if you remove Sizzle from the window while bootstrapping your code you'd be good to go.

Sample Sizzle bug that could possible be introduced.

https://github.com/jquery/sizzle/issues/322

Please update if it works, I'm closing this, since it's an issue with D3/Sizzle.  Good luck.
