### ISSUE TITLE
Rotate axis issue with 0.4.11

### ISSUE THREAD

**Issue by Dhruva2015** [masayuki0812/c3#1210]
1. When axis is rotated in c3js (0.4.11 pre release) multiple x axis lines are visible.
2. axis.x.height is also not working when axis is rotated.

**Comment by markdboyd** [comment]
I am also seeing these issues with c3 JS 0.4.11

**Comment by masayuki0812** [comment]
https://github.com/masayuki0812/c3/pull/1294 fixes 1. For 2, I'm investigating now.

**Comment by masayuki0812** [comment]
For 2, `padding.left` should be used. So, all seems to be ok now.

**Comment by aendrew** [comment]
This seems resolved, so closing.
