### ISSUE TITLE
(0.4.11-rc1) Incorrect layout when using titles on charts that are not visible at generation

### ISSUE THREAD

**Issue by laurence-hudson-tessella** [masayuki0812/c3#1225]
Example here: http://codepen.io/anon/pen/aOLwGd.
Title is above the top of the SVG.

0.4.11-rc1 - 4b34a19 
#1199

Note: codepen example doesnt work at all in firefox due to #1160(#131). but title bug can be seen in chrome. Firefox specific issue is resolved by PR #1226 (http://codepen.io/anon/pen/aOLyEL), but layout issue still present.

**Comment by laurence-hudson-tessella** [comment]
Caused by getBBox and getBoundingClientRect (used to determine the size of the text) returning 0s for elements contained within a "display: none"

**Comment by aendrew** [comment]
:+1: Confirming.
