### ISSUE TITLE
Incorrect x tick positioning, for some data ranges

### ISSUE THREAD

**Issue by laurence-hudson-tessella** [masayuki0812/c3#1229]
See http://codepen.io/anon/pen/xGPVgJ?editors=001
Correct tick values, but placed at wrong position on x axis.

**Comment by deepak-singla** [comment]
just remove count=5 and add fit: true

 axis: {
   x: {
    tick: {
     fit: true,
     format: function (x) { return Number(x.toPrecision(2)); }
    },
   }

**Comment by laurence-hudson-tessella** [comment]
That's not the point. 

There is a bug when the alphabetic sorting of the ticks is not the same as the numeric sorting. 

As it happens for this data set using the fitted ticks will generate ticks that have the same sort order, but the bug is still present. There will be data sets for which the fitted sort order displays incorrectly.

I have provided a fix for this bug. It is just waiting to be merged.
