### ISSUE TITLE
Touch drag to show different tooltips

### ISSUE THREAD

**Issue by sanderbaas** [masayuki0812/c3#1236]
Is there an option to show tooltips while dragging over the chart on a touch device? With a mouse it is possible to hover over the graph so that tooltips are show, on a touch device a tap shows a tooltip. But I would like to drag over the chart like in this example of Highcharts: http://www.highcharts.com/demo/line-basic .

**Comment by aendrew** [comment]
@sanderbaas That's definitely not supported out of the box, though could be possible by listening to the `touchmove` event.

Mind asking in the [Google Group](https://groups.google.com/forum/#!forum/c3js)? It's better suited for this type of question.

Thanks!
