### ISSUE TITLE
Reduce height of Gauge container - reduce empty area on top

### ISSUE THREAD

**Issue by soufi** [masayuki0812/c3#1237]
Hi,

First of all thank you for this great library.

I would like to know if there is anyway to reduce the height of Gauge Chart container in order to reduce the empty area on top of the chart : 

![fullscreen_24_06_15_18_43](https://cloud.githubusercontent.com/assets/3698951/8336084/25c9caca-1aa2-11e5-88ad-5108b6432a30.png)

I tried the following : 

```css
.c3 > svg {
    max-height: 120px;
} 
```
But the chart is cut as you can see : 

![screen shot 2015-06-24 at 18 55 46](https://cloud.githubusercontent.com/assets/3698951/8336174/befdbd32-1aa2-11e5-9cb0-a0b82920b802.png)

And the thing that i can't understand is :  when I resize the window or change browser tab the chart automatically resizes itself and became just perfect ! 

![screen shot 2015-06-24 at 18 59 35](https://cloud.githubusercontent.com/assets/3698951/8336219/309700b6-1aa3-11e5-8f77-ad5c472abac4.png)

I tried to retrieve this programatically by firing the event **resize** but it didn't work.

I am using Dojo + Bootstrap. 

Thanks.

**Comment by Eden-Sun** [comment]
try add "chart-size" tag for your chart ,
```
 <c3chart bindto-id="xxx" chart-data="somedata" chart-columns="somecolumns">
        <chart-size chart-height="80" chart-width="140"></chart-size>
        .
        .
      </c3chart>
```

**Comment by soufi** [comment]
This is the first thing I should've tested ! It worked ! thanks a lot Eden-Sun !
