### ISSUE TITLE
Global defaults

### ISSUE THREAD

**Issue by seppentoni** [masayuki0812/c3#1240]
Is it possible to set global defaults sitewide?

For example: I want to have all circles a radius of 5. Instead of writing it in each and every chart I want to set that globaly.

Is this possible? (I already asked this in the google forums but since nobody replied I guess this is a feature request,)

**Comment by aendrew** [comment]
Hi @seppentoni!

Actually, looking at the code a bit, seems there's an undocumented feature for this already — could you try attaching your config to `chart.internal.fn.additionalConfig` on the global `c3` object (So `window.c3.chart.internal.fn.additionalConfig` in browser) and seeing whether that does this?
