### ISSUE TITLE
Bar width ratio with subchart zoom broken in 0.4.10

### ISSUE THREAD

**Issue by elnino1** [masayuki0812/c3#1241]
Hi,

I try to have the bar width ratio updated when zooming via subchart.
After many tries, I finally found that it is working with 0.4.9 but not with 0.4.10.

The following code shows the point:
```
<html>
  <head>
    <title></title>
    <meta content="">
    <style></style>
    
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js" charset="utf-8"></script>

<!-- switch to 0.4.10 breaks the bar ratio-->
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/c3/0.4.9/c3.js"></script>
<link href="http://cdnjs.cloudflare.com/ajax/libs/c3/0.4.9/c3.css" rel="stylesheet" type="text/css">

  </head>
  <body>

<div id="chart"></div>
<script>

var rows = [
	  ["date","A","B","C","D","E","F"],
	  [1435140000000,0,2,2,2,0,0],
	  [1435226400000,1,3,2,0,0,1],
	  [1435312800000,0,2,0,0,1,2],
	  [1435399200000,1,0,2,1,2,0],
	  [1435485600000,0,0,2,1,1,1],
	  [1435572000000,0,0,1,0,0,0]
        ];

var config = {
  data: {
    type: 'bar',
    x: 'date',
    rows: rows
  },
  subchart: {show: true}
};
        
c3.generate(config);

</script>
</body>
</html>
```

With 0.4.9, when zooming the bar width adapts to the selected range.
With 0.4.10, zooming has no effect on the bar width which is the same as in sub chart.

If this is a bug, I'll wait for next version. However if it is the intented behavior, it will be useful to have an option to manage the bar ratio as previoulsy.
It is especially useful when having high number of X points to be zoomed.

Regards.

**Comment by DanielApt** [comment]
Seeing this issue as well, `v0.4.10` introduces this bug.

**Comment by aendrew** [comment]
Ah, yep indeed. It's the same bug as #1254, please direct efforts there.
