### ISSUE TITLE
Holes in Data in Line/Area chart.

### ISSUE THREAD

**Issue by ErikTech** [masayuki0812/c3#1242]
Hi there. I was wondering if there was a way to add holes in the data. Such as have a line on a line graph simple stop on the 3rd axis point, and then continue again on the 4th, leaving a gap between it.

Currently making the values  'null' make the line go back down to 0 by the next axis point. I want it to simply stop drawing the line until there is an actual value again instead of 'null'.

Let me know if you need for me to explain further.

**Comment by aendrew** [comment]
I'm not sure where you're getting `null` starting the data at zero; unless you've actually put a literal `0`?

![screen shot 2015-07-02 at 13 58 39](https://cloud.githubusercontent.com/assets/185041/8477489/7982b61a-20c2-11e5-9c16-e48f40dcccef.png)

http://jsfiddle.net/aendrew/auz6rgs4/1/

Closing as more of a support request than an issue. Could you please ask such questions in the [C3 Google Group](https://groups.google.com/forum/#!forum/c3js)? Thanks!
