### ISSUE TITLE
Is it possible to set tick count for multiple custom x?

### ISSUE THREAD

**Issue by eddiesong** [masayuki0812/c3#1244]
For example:

var chart = c3.generate({
    data: {
        xs: {
            data1: 'x1',
            data2: 'x2'
        },
        columns: [
            ['x1', '2013-01-01', '2013-01-03', '2013-01-04', '2013-01-05', '2013-01-06', '2013-01-07', '2013-01-08', '2013-01-09', '2013-01-10', '2013-01-11', '2013-01-12'],
            ['data1', 30, 100, 400, 150, 250, 30, 200, 100, 400, 150, 250],
            ['x2', '2013-01-01', '2013-01-02', '2013-01-03', '2013-01-05', '2013-01-06', '2013-01-07', '2013-01-08', '2013-01-09', '2013-01-10', '2013-01-11', '2013-01-12'],
            ['data2', 30, 200, 100, 200, 130, 250, 280, 100, 400, 150, 250]
        ]
    },
    axis: {
        x: {
            type: 'timeseries',
            tick: {
                count: 10,
                format: '%Y-%m-%d'
            }
        }
    }
});

It shows something like this:

![axes_x_tick_count](https://cloud.githubusercontent.com/assets/5259520/8438771/020bd018-1f36-11e5-8b17-a53c8f3b4417.png)

Is there a way to make tick count dynamically adjusted to all x axis combined?

**Comment by aendrew** [comment]
Closing as more of a support request than an issue. Could you please ask such questions in the [C3 Google Group](https://groups.google.com/forum/#!forum/c3js)? Thanks!
