### ISSUE TITLE
Different text colors on the same axis?

### ISSUE THREAD

**Issue by Palladian1881** [masayuki0812/c3#1245]
Hi,

Is it possible to have multiple text colors for ticks along the same axis? Here's what I need:
![image](https://cloud.githubusercontent.com/assets/8864735/8461575/ef274c06-1fea-11e5-808d-480f915c8ca0.png)

Thanks!

**Comment by aendrew** [comment]
Probably with CSS, using `:nth-child` pseudoselectors.

Closing as more of a support request that an issue. Could you please ask such questions in the [C3 Google Group](https://groups.google.com/forum/#!forum/c3js)? Thanks!
