### ISSUE TITLE
Extra x-axis appearing upon resize

### ISSUE THREAD

**Issue by Palladian1881** [masayuki0812/c3#1246]
Hi,

Here is my graph. It is required to be resizable:
![image](https://cloud.githubusercontent.com/assets/8864735/8462907/10ffc5fc-1ff4-11e5-9a70-2e9df9d4cce0.png)

When I resize it, however, another x-axis appears:
![image](https://cloud.githubusercontent.com/assets/8864735/8462917/28b51d64-1ff4-11e5-9c89-28942c2277b0.png)

Here is my code. Thanks!

    <head>
    <script>
    var randomBetween = function(min,max){
         return Math.random() * (max-min) + min;
    }
    $(function() {
        $( "#windowDiv" ).resizable();
        var chart = c3.generate({
             bindto: '#chart',
              data: {
                 columns: [
                          ['Reports_Generated', randomBetween(0,500),randomBetween(0,500),randomBetween(0,500),randomBetween(0,500),randomBetween(0,500),randomBetween(0,500),randomBetween(0,500),randomBetween(0,500),randomBetween(0,500),randomBetween(0,500),randomBetween(0,500),randomBetween(0,500)],
                          ],
                 type: 'spline',
             }
    });

    $("#windowDiv").resize(function(){
             chart.resize({
                 height: $("#windowDiv").height() - 40,
                 width: $("#windowDiv").width() - 20
             });
        });
    });
  
    </script>
    </head>
    <body>
    <div id="windowDiv" style="width:404px;height:414px;border:1px  solid black;">
    <div id="chart"></div> 
    </div> 
    </body>

**Comment by Palladian1881** [comment]
Turns out that the second x axis was always there, it was just hidden initially. I fixed the problem by removing the duplicate axis:
    $('.c3-axis-x').eq(1).remove();

Not a great solution, but it works.

**Comment by aendrew** [comment]
I'm experiencing this too after updating to 0.4.11-rc1 in Axis, and I don't even need to resize the browser window. Investigating a bit further, it's actually the subchart x-axis, and changing the style property from `visibility: hidden` to `display: none` hides it. I'm not sure what the issue is; if [I just rip that bit of code out and put it in a jsFiddle](http://jsfiddle.net/aendrew/nypacLt9/), it's still visible, even without any CSS to override it or anything. Rather confused, behaviour persists in both Firefox and Chrome.

**Comment by aendrew** [comment]
I've figured it out, pretty edge-case-y — if somehow `subchart.visible` is `false` and `subchart.x.axis.show` is `true`, and the SVG area gets extended, the subchart axis is visible. PR in the works...

**Comment by aendrew** [comment]
Actually, this is way less edge-case than I thought — `subchart.x.axis.show` is truthy by default, all you need to do is [extend the SVG area](http://jsfiddle.net/aendrew/Lr6dbgwb/6/) and it's visible.

**Comment by daxfohl** [comment]
For now you can get around the issue by configuring the chart with `subchart: { axis: { x: { show: false } } }`
