### ISSUE TITLE
omit first element from pie chart

### ISSUE THREAD

**Issue by JosephOR** [masayuki0812/c3#1247]
Hey,
I am creating a pie chart using the column data layout. the data I pass in is each 3 items long:
main array =
[
 [1, desc1, 62]
 [2, desc2, 34]
]

the first element is an id, which i need to use when i click on a pie segment. the problem is that the chart uses this number and ads it to 62 in the first case. is there a way of not using all elements in the array, such as omit innerArray[0] for each array in mainArray?

cheers,
joey

**Comment by aendrew** [comment]
This isn't really an issue and more of a support request. Could you please ask in the [C3 Google Group](https://groups.google.com/forum/#!forum/c3js)? Thanks!
