### ISSUE TITLE
0.4.11 breaks stacked area plots

### ISSUE THREAD

**Issue by tom-christie** [masayuki0812/c3#1315]
Using 0.4.10 and a plot of type "area" I can group all data series using chart.groups(), and the lines stack. I can't get that to work in 0.4.11-rc3 - the series remain non-stacked.

**Comment by ChrisTitos** [comment]
I have the same issue. Seems to go wrong in every RC version of 0.4.11

**Comment by masayuki0812** [comment]
Sorry this is a bug and I think it's has been fixed now.

**Comment by ChrisTitos** [comment]
Thanks, it works correctly now.

**Comment by aendrew** [comment]
This seems resolved so closing.
