### ISSUE TITLE
Question: X axis at top of chart? 

### ISSUE THREAD

**Issue by upphiminn** [masayuki0812/c3#1358]
Is it possible to have the X axis at top of the chart instead of the bottom? I couldn't find any option for it nor any discussion on it.

**Comment by sivagnanamn** [comment]
In D3.js the x axis has an attribute ' .attr("transform", "translate(0," + height + ")") '. If we don't add this line x-axis will be on top of the chart. Something similar to this should be available in C3 too.

**Comment by ruudboon** [comment]
d3.select('c3-axis-x').attr("transform", "") works to get the axis on top. But when new data comes in using  the load function the transform is reset. What's the best option to keep this permanent?

**Comment by af-sko** [comment]
Is there a solution for this problem?
So far changing the attribute seems to work, but it doesn't feel good ;)

**Comment by upphiminn** [comment]
@af-sko I think I used the y2 axis as x and rotated ...
