### ISSUE TITLE
react+c3: tooltip not working

### ISSUE THREAD

**Issue by luisrudge** [masayuki0812/c3#1376]
Hi, I have a repro here: https://github.com/luisrudge/c3-react

Tooltips are not working when using react
![c3](https://cloud.githubusercontent.com/assets/941075/9750777/ebc936c8-5672-11e5-8e90-ee746eeb0e7e.gif)

**Comment by luisrudge** [comment]
I hosted this example: http://c3-react.azurewebsites.net/

**Comment by laurence-hudson-tessella** [comment]
Duplicating the fix from gitter here, for anyone else with the same issue.
The "bindto" element should be a normal HTML DOM element, not an SVG element. C3 will create the SVG inside the bindto element.

**Comment by luisrudge** [comment]
Yep. That was it. Thanks very much!
