### ISSUE TITLE
Add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by aendrew** [masayuki0812/c3#1418]
The issue queue is a huge mess right now (largely my fault due to not doing my job... :sweat_smile:), and it isn't getting better and requires a lot of manual involvement.

Adding a CONTRIBUTING.md does the following:

1. Shows a notice at the top of new issues requesting the submitter read the guidelines before submitting an issue. Hopefully some will actually do that and instead go to Gitter or Google Groups.
2. Gives us a place to write down community standards, etc.

Everyone in support of this idea? If so, what all should we put in it?

**Comment by kobalicek** [comment]
Agree, I did one PR and I didn't know what is the proper way, I would personally try to avoid having combined and minified files in the main repo, it makes things confusing for me.

**Comment by aendrew** [comment]
Fixed in 8b520aac635c53dcbc3dd286ad03d54929ed9271.
