### ISSUE TITLE
Zoom not working 

### ISSUE THREAD

**Issue by eregnier** [masayuki0812/c3#1441]
The zoom system seems to not work on the current release on desktop devices.

I tried http://c3js.org/samples/interaction_zoom.html 
to drag and drop the chart and double click on the chart bot nothing appends.

Nothing appeared in the console.

Tested on firefox 41 and google chrome 45

**Comment by aendrew** [comment]
@eregnier Zoom on desktop is controlled by mousewheel. I just tried it in both Firefox and Chrome and it works as expected. 

Closing as invalid because it seems to work as expected. If I'm incorrect in this assertion, please let me know and I'll reopen. Thanks!

**Comment by eregnier** [comment]
It's ok for me now, I didn't know and didn't tried to do it thanks to the mousewheel. 

Thank you :)
