### ISSUE TITLE
Bar.label.show option

### ISSUE THREAD

**Issue by hudecsamuel** [masayuki0812/c3#1444]
I was working on a bar chart recently and noticed there is no option to hide labels on bar chart even though there is this option on other types of your charts.
I had to display ```values``` on __X__ axis and total ```occurences``` on __Y__ axis.
The problem that arose was that when i had longer strings in ```values``` the labels begin to be nasty. 

![screenshot from 2015-10-27 14 08 57](https://cloud.githubusercontent.com/assets/13395909/10759844/00c4d6aa-7cba-11e5-9f84-73e3fed08b2a.png)

So I thought that i dont need them there, just the hover tooltip was OK. I looked for the solution but found out that there is this option in pie, donut etc. but not for Bar chart. I also tried to show: false the __X__ axis, wich was fine if the values were short, but the elements were just hidden so it caused something like this:
![screenshot from 2015-10-27 14 08 33](https://cloud.githubusercontent.com/assets/13395909/10759762/8d2f82ee-7cb9-11e5-90f8-412cddc542e1.png)

When the values were short it looked fine:
![screenshot from 2015-10-27 14 15 39](https://cloud.githubusercontent.com/assets/13395909/10759819/e124cfe4-7cb9-11e5-961c-fdfe93ece209.png)

A simple option to disable labels on axis in Bar chart would be nice :)

**Comment by davidpoore** [comment]
There is a way to do this using existing chart config options:

```
axis: {
  x: {
    tick: {
      format: function () { return ''; }
    }
  }
}
```

This will return an empty string as the tick value for every label on x-axis.

**Comment by hudecsamuel** [comment]
Thanks, that solved my problem.
