### ISSUE TITLE
Changing Tick Length

### ISSUE THREAD

**Issue by J-L** [masayuki0812/c3#1455]
Is there a CSS property to change the Tick Length of the axis'?

I am drawing on a small display and the ticks are very stubby.

Thank you

**Comment by aendrew** [comment]
Hi @J-L! This is more of a support question — would you mind please asking instead on the [C3 Google Group](https://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) channel? Thanks!
