### ISSUE TITLE
Provide a way to programatically change x axis type (ex. timeseries, category, index)

### ISSUE THREAD

**Issue by guywithcrookedface** [masayuki0812/c3#1456]
Hi, I'm trying to provide a UI option to enable/disable timeseries rendering of a C3 chart. However, I don't see a way to programatically do this without re-creating the chart with the data.x.type changed to the type I want.

Could you please add an option that allows us to change the x axis type via a method similar to the other accessor methods that are provided?

Thanks!

**Comment by aendrew** [comment]
Hi @guywithcrookedface! We're collecting issues that involve improve the post-generation API at #1480. Please concentrate discussion there — thanks! Closing as duplicate.

**Comment by guywithcrookedface** [comment]
Hi @aendrew, will do. Thanks!

**Comment by moosilauke18** [comment]
Hi, I can't seem to find anything about this. Did this ever get implemented?
