### ISSUE TITLE
Interactive examples

### ISSUE THREAD

**Issue by missingdays** [masayuki0812/c3#1461]
When I'm trying to edit examples on c3js.org, they redraw after each letter I type. So is I type "chart.load({columns:[['data1', 10, 20, 30]]});" it will redraw chart like 30 times, though I don't want it to be redrawed after I typed "c", then "h" and so forth.
Can you please add timeout for redrawing examples? Like if user didn't type anything for 200 milliseconds, then redraw.
Thanks!

**Comment by aendrew** [comment]
@missingdays Yeah, totally agree. We need to put the change handler into some sort of debouncing function, possibly something like:

```js
function debounce(func, wait, immediate) {
	var timeout;
	return function() {
		var context = this, args = arguments;
		var later = function() {
			timeout = null;
			if (!immediate) func.apply(context, args);
		};
		var callNow = immediate && !timeout;
		clearTimeout(timeout);
		timeout = setTimeout(later, wait);
		if (callNow) func.apply(context, args);
	};
}
```

Source: https://davidwalsh.name/function-debounce

This is more relevant to masayuki0812/c3js.org though, so closing and moving discussion there.

**Comment by missingdays** [comment]
Agreed, didn't notice there is another repo for c3js.org
