### ISSUE TITLE
Baseline on c3 multiseries graph

### ISSUE THREAD

**Issue by misticini** [masayuki0812/c3#1470]
Hello,

I'm using c3 to draw some multiseries graphs but i'm having some problems. I wanna draw a graph with baseline but c3 always adjust x axis to adapt to the all range of data. I'll give an example:

```javascript
var chart = c3.generate({
    data: {
        xs: {
            'data1': 'x1',
            'data2': 'x2',
        },
        columns: [
            ['x1', '2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04', '2013-01-05', '2013-01-06'],
            ['x2', '2012-01-01', '2012-01-02', '2012-01-03', '2012-01-04', '2012-01-05', '2012-01-06'],
            ['data1', 30, 200, 100, 400, 150, 250],
            ['data2', 130, 340, 200, 500, 250, 350]
        ]
    },
    axis: {
        x: {
            type: 'timeseries',
            tick: {
                format: '%Y-%m-%d'
            }
        }
    }
});
```

I want that above graphic draw 2 lines but the x axis only show the values of x1, but when i click in a point of data2 line i want that the legend show the values of x2. Is that possible?

**Comment by aendrew** [comment]
Hi @misticini! This is more of a support question — would you mind please asking instead on the [C3 Google Group](https://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) channel? Thanks!
