### ISSUE TITLE
Is there a way to add value data in legend ?

### ISSUE THREAD

**Issue by julestruong** [masayuki0812/c3#1473]
Could it be possible to format the display of legend like it is possible to do for a tooltip ? With index, value, ratio etc ...

**Comment by aendrew** [comment]
Hi! This is more of a support question — would you mind please asking instead on the [C3 Google Group](https://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) channel? Thanks!
