### ISSUE TITLE
Connecting plot when a value is missing

### ISSUE THREAD

**Issue by chandon** [masayuki0812/c3#1474]
I've 2 data series, but i've got missing values for each serie (data1, x=2 and data2, x=3)

I've set data to 'null' value for holes, but it doesn't render correctly. I know i could interpolate the missing value, but i don't want a "plot" and a value to be shown in the tooltip.

Is there a way to solve this problem ?
Thanks

    var chart = c3.generate({
        data: {
            columns: [
                ['data1', 300, 200, null, 300, 0, 0],
                ['data2', 130, 100, 140, null, 150, 50]
            ],
            types: {
                data1: 'area',
                data2: 'area'
            }
        }
    });

https://jsfiddle.net/bt56r29q/448/

**Comment by lmh** [comment]
http://c3js.org/reference.html#line-connectNull
Seems to be exactly what you're asking for.

**Comment by chandon** [comment]
@imh Exactly, thanks a lot ! I didn't see this option...
