### ISSUE TITLE
How can i add space between group c3 bar chart?

### ISSUE THREAD

**Issue by sole6** [masayuki0812/c3#1475]
I am trying to add space between grouped bar chart.
Is there a way to do that?
![c3 bar](https://cloud.githubusercontent.com/assets/9457841/11389882/bcfef358-9355-11e5-9fa9-9502c77c1202.PNG)

**Comment by aendrew** [comment]
Hi! This is more of a support question — would you mind please asking instead on the [C3 Google Group](https://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) channel? Thanks!
