### ISSUE TITLE
Group JSON Data for x axis

### ISSUE THREAD

**Issue by Red120** [masayuki0812/c3#1476]
Hi,
 I have something like this:
//----------------------------------------------------------------------------------------------------------------
<div id="chart"></div>
<script type="text/javascript">
var chart = c3.generate({
bindto: '#chart',
data: {
json: [{"date":"Sep","2013":"0"},{"date":"Okt","2013":"0"},{"date":"Nov","2013":"0"},{"date":"Dez","2013":"0"},{"date":"Jan","2014":1500},{"date":"Feb","2014":"0"},{"date":"Mar","2014":"0"},{"date":"Apr","2014":"0"},{"date":"Mai","2014":"0"},{"date":"Jun","2014":400},{"date":"Jul","2014":"0"},{"date":"Aug","2014":500},{"date":"Sep","2014":1200},{"date":"Okt","2014":"0"},{"date":"Nov","2014":"0"},{"date":"Dez","2014":"0"},{"date":"Jan","2015":"0"},{"date":"Feb","2015":"0"},{"date":"Mar","2015":"0"},{"date":"Apr","2015":500},{"date":"Mai","2015":"0"},{"date":"Jun","2015":"0"},{"date":"Jul","2015":1700},{"date":"Aug","2015":"0"},{"date":"Sep","2015":500},{"date":"Okt","2015":"0"},{"date":"Nov","2015":"0"}],
          keys: {
            x: 'date',
            value: [ "2013", "2014", "2015" ]
          },
		  type: 'line'
        },
        axis: {
          x: {
            type: "category"
          }
        }
	});
//----------------------------------------------------------------------------------------------

I get a chart as result, that shows me Months from Sep 2013 until Nov 2015 and three lines basing on Month/Jear. One after an other.

Is it possible to group my x-date-key so that I get 3 chart-lines (2013,2014 and 2015) in one chart with 1 time months from January to December?

If not, what do I have to change to get the result I want to have?

Best regards

Frank

**Comment by aendrew** [comment]
Hi! This is more of a support question — would you mind please asking instead on the [C3 Google Group](https://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) channel? Thanks!
