### ISSUE TITLE
I make multi ring chart successfully, but I can not make adjusted legend

### ISSUE THREAD

**Issue by say8425** [masayuki0812/c3#1524]
Hello I want to make multi ring donut chart.
So I find other chart library.
But I think maybe is it possible make with c3 and css. So I try it.
Here is my result.

https://jsfiddle.net/say8425/xtr6jo5m/

Well, It's not well designed but anyway it works.
However one thing is missed It's the legend.
I hide legend of middle and inner chart.
So only outer legend is shown. And when I hover or click it just works on outer.

I try this legend works on middle and inner chart.
But I don't know well about d3 so it's fail.
How can I apply this legend works with middle and inner chart?

**Comment by say8425** [comment]
I complete with [legend.item](http://c3js.org/reference.html#legend-item-onclick)
https://jsfiddle.net/say8425/45gro44n/1/

**Comment by aendrew** [comment]
That is absolutely crazy but is also awesome. Props! :+1:

Closing because it seems you've resolved your issue; if not, please ask on the Google Group. Thanks!
