### ISSUE TITLE
Mismatch between regions and bars in timeseries barchart

### ISSUE THREAD

**Issue by AbeHandler** [masayuki0812/c3#1538]
Hi, 

I found an inconsistency in how c3js handles time series bar charts.

This example shows a region from Jan 1 to Jan 4, 2013, along with data for January 1, 2013: http://jsfiddle.net/abe_handler/8j6j4oh4/3/

The bar for January 2013 extends into 2012 because c3js centers the January 2013 data on the tickmark. 

This makes it hard to use c3 to render a bar chart on a time series with a region

<img width="441" alt="screen shot 2016-01-17 at 1 29 25 am" src="https://cloud.githubusercontent.com/assets/1252925/12376297/c9c903f2-bcb9-11e5-8a2b-d837df18a9c9.png">

**Comment by AbeHandler** [comment]
https://github.com/masayuki0812/c3/issues/65

**Comment by DerManoMann** [comment]
Looking at the same issue right now - was there a solution?
