### ISSUE TITLE
Adding a Marker to the Gauge 

### ISSUE THREAD

**Issue by dava2788** [masayuki0812/c3#1559]
I have a case that use the gauge to show the current value in comparison to a target value.. The target could be smaller or larger than the current value. If there is an option to add a marker to the gauge like in the following mock-up screen, it will help a lot..

![image](https://cloud.githubusercontent.com/assets/1749777/12589962/219c1a38-c426-11e5-859d-3a4233a618c0.png)

**Comment by aendrew** [comment]
Hi @dava2788! This is more of a support question — would you mind please asking instead on the [C3 Google Group](https://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) channel? Thanks!
