### ISSUE TITLE
Could I use jsp to print the JSON for C3 charts?

### ISSUE THREAD

**Issue by XidongHuang** [masayuki0812/c3#1563]
Hi, C3 examples use .cvs and .json file to be url source for charts. 
But could I just .jsp file to communicate to the back-end then print JSON as String instead of .json files? 
like:
hello.jsp
`<script type="text/javascript">
		var chart = c3.generate({
			bindto : '#chart',
			data : {
				url: 'chartJSON.jsp',
				mimeType:'json'
			}
		});
	</script>`

and chartJSON.jsp:
`<%
     String json = 
     "{\"data1\": [220, 240, 270, 250, 280],\"data2\": [180, 150, 300, 70, 120],\"data3\": [200, 310, 150, 100,       180]}";	
%>
	<%= json %>`

The chart cannot parse the .jsp file, so just want to ask could I just JSON like that? Or I have to put a JSON in .json file?
Thanks!

**Comment by aendrew** [comment]
@XidongHuang My guess is that it'll be fine so long as  chartJSON.jsp returns valid JSON (which it doesn't at the moment; remove `json = `) and the server sets MIME type to `application/json`.

That said, this is more of a support question than an issue; mind asking on the [Google Group](https://groups.google.com/forum/#!forum/c3js)? Thanks!
