### ISSUE TITLE
Donut chart: dynamically changing order

### ISSUE THREAD

**Issue by pmourlanne** [masayuki0812/c3#1568]
I have a donut chart, and I want to be able to switch between `null`, `desc` and `asc` orders. The `order` option work properly when the chart is generated, but seems to be ignored on subsequent `load` calls.

Here is a fiddle of what I'm talking about: https://jsfiddle.net/rd32pxbt/6/

I expected the order of the chart to change on each load call. Am I doing something wrong or is this a bug?

**Comment by raphaelgera** [comment]
I don't think the load call is meant for changing the configuration, I think it is used for the data.
You can achieve what you want by regenerating the chart:
chart = c3.generate(options);
and I am not sure if you need to destroy it first or not:
chart = chart.destroy();
chart = c3.generate(options);

**Comment by pmourlanne** [comment]
A `generate` call doesn't work as you can see quickly in my jsfiddle by replacing the `load` call with a `generate` one.

I do not want to destroy the chart to change the order, because I have attached bindings to the chart at this point.

**Comment by raphaelgera** [comment]
Not sure I follow you. you can't call generate on the chart that doesn't exist. you can use the example from above instead of load. In the jsfiddle it works. Can't see what you are binding to though, so I can't help you there...

**Comment by pmourlanne** [comment]
Sorry, I wasn't clear enough. Indeed, there are no bindings in the fiddle I linked, because it's a simple example of what I'm trying to achieve. In production, when I want to change the order, I have already attached bindings to the chart, and I would not want to destroy it and re-attach the bindings.

What do you mean by `In the jsfiddle it works`? Do you mean that destroying the chart and generating it changes the order?
If so, I do not doubt it but I'm trying to change the order of the chart _without having to destroy it_ (that, I know how to do).

**Comment by aendrew** [comment]
Hi @pmourlanne! This is more of a support question — would you mind please asking instead on the [C3 Google Group](https://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) channel? Thanks!
