### ISSUE TITLE
Chart frozen in jQuery UI Dialog

### ISSUE THREAD

**Issue by MihaiBratulescu** [masayuki0812/c3#1575]
I am making my chart in a dialog and whenever I reopen the dialog the chart there is frozen. I have tried to redraw it using flush but it still makes no difference. Is there anything that can be done?

**Comment by aendrew** [comment]
Hi @MihaiBratulescu! This is more of a support question — would you mind please asking instead on the [C3 Google Group](https://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) channel? Thanks!
