### ISSUE TITLE
Styling tick differently for shown culled values

### ISSUE THREAD

**Issue by jasonlally** [masayuki0812/c3#1579]
I've been looking for a simple way to style tick lines that correspond to shown values when culling is in place, for example on a time series chart.

While the user can mouseover and see what the values are in the tooltip, I find its a nice quick visual way to help users associate the x tick label with the appropriate line, particularly when tick marks are more crowded.

I couldn't find a simple css selector to do this. Is there an API feature I'm missing? Couldn't find anything in the issues/docs.

Any help appreciated.

If this isn't possible, it would be great to have this as an option, maybe by simply passing a class to the line that one could style.

`.c3 line.value-showing`?

**Comment by aendrew** [comment]
Hi @jasonlally! This is more of a support question — would you mind please asking instead on the [C3 Google Group](https://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) channel? Thanks!
