### ISSUE TITLE
How to get chart object using selector

### ISSUE THREAD

**Issue by gangwar1** [masayuki0812/c3#1580]
Hi,

when we generate chart at that time we get the object of chart.
`var chart = c3.generate({
  bindTo: '#chart',
  data: {
        columns: [
            ['data1', 100, 200, 150, 300, 200],
            ['data2', 400, 550, 250, 700, 300],
        ]
    }
});`

if we not maintain this chart object for further operation in that case we can get the above object using selector or any other way .
if yes please share it how ?

it is necessary to get chart object to apply any functionality  .

**Comment by aendrew** [comment]
Hi @gangwar1! This is more of a support question — would you mind please asking instead on the [C3 Google Group](https://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) channel? Thanks!
