### ISSUE TITLE
How to rotate c3.js xgrid text

### ISSUE THREAD

**Issue by heenaI** [masayuki0812/c3#1585]
How can I rotate xgrid values of C3. every time I try to use css rotate the text disappears. js fiddle: http://jsfiddle.net/yrzxj3x2/7/

here is the css that I have tried for complete code see js fiddle

.xLineLable text{
  font-size: 12px;
}
.c3-grid text {
    fill: #000;
    transform: rotate(7deg);
  }

**Comment by aendrew** [comment]
Hi @heenaI! This is more of a support question — would you mind please asking instead on the [C3 Google Group](https://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) channel? Thanks!
