### ISSUE TITLE
Is it possible to have hh:mm:ss at y axis?

### ISSUE THREAD

**Issue by ndabAP** [masayuki0812/c3#1587]
Hi, I asked this in the Google Groups before but got no answer so I ask it here. Can I have data at the y axis with format `hh:mm:ss`?

**Comment by aendrew** [comment]
That should be possible, but I'm not sure whether it is due to time generally always being on the X-axis as per convention. Can you maybe put time on the x-axis and then rotate the chart, if you need time on a vertical axis?

**Comment by aendrew** [comment]
Closing as not really a bug; please feel free to respond if my suggestion doesn't work and we can possibly rework this into a feature request. Thanks!

**Comment by ndabAP** [comment]
Thank you, @aendrew. I'll give it a try.

**Comment by ndabAP** [comment]
Or is it possible to use different data than it shows. If so, I would convert my array to seconds and use the `hh::mm:ss` values AS texts.

**Comment by ndabAP** [comment]
The problem is that my x values are dates. 

`x: '2014-01-01', '2014-01-03', 2014-01-04', ...
y: '01:00:30', '00:55:00', '02:30:10', ...`

**Comment by aendrew** [comment]
Oh, I see what you're doing — you're setting dates as the x-axis, and times as the y-axis? You could convert those into minute or second durations (I.e., "how many minutes/seconds after midnight is each value?"), plot those as bars or whatever, and then just convert back using a formatter? It's a bit of a pain, but the only way with C3 at the moment AFAIK.
