### ISSUE TITLE
Is there a way to add a class to a c3 object?

### ISSUE THREAD

**Issue by taichatha** [masayuki0812/c3#1588]
I am trying to add a background to a c3 gauge, and an issue that occurs when I have multiple gauges is that both backgrounds end up being hooked up to the first gauge that gets rendered because I am d3.selecting (.c3-chart-arcs) and then inserting the background as the first child. So my question is, is there a way to effectively add a class to a c3 object, particularlly the c3-chart-arcs g element. 

I tried doing d3.select('c3-chart-arcs').node().setAttribute, but it always ends up breaking for both of them. And doing d3.classed() doesn't work either.

**Comment by aendrew** [comment]
Hi @taichatha! This is more of a support question — would you mind please asking instead on the [C3 Google Group](https://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) channel? Thanks!
