### ISSUE TITLE
disable fade in effect when chart is rendered

### ISSUE THREAD

**Issue by luisrudge** [masayuki0812/c3#1598]
is it possible?

**Comment by linearza** [comment]
This is what you might be looking for:
http://c3js.org/reference.html#transition-duration

**Comment by luisrudge** [comment]
ohh, right under my eyes :D Thanks!

**Comment by pistou** [comment]
This disable both fade **and** animation on `.load()`.
Is there a way to disable **only** the fade effect?

**Comment by forteddyt** [comment]
I am also curious as to if I can disable to fade in effect, specifically. Are there any ways to do that?
