### ISSUE TITLE
Float value bug

### ISSUE THREAD

**Issue by musaakkayaa** [masayuki0812/c3#1599]
Hi,
İ have a problem like attachment file,
float values is return to bad situation
![bug](https://cloud.githubusercontent.com/assets/17456219/13291622/1f25e11e-db21-11e5-8b9e-b6436dac26a4.png)

**Comment by avcs06** [comment]
I am also facing the same issue, did you find any solution?

**Comment by musaakkayaa** [comment]
I made a solution like this
tspan.text(function (d) {
                    var n = parseFloat(d.splitted);
                    return (d.splitted % 1 === 0) ? d.splitted : n.toFixed(2);
                });

line:6852

**Comment by avcs06** [comment]
thank you @musaakkayaa

**Comment by aendrew** [comment]
It's quite possible that could be a bug, but it's really hard to verify it without more information. We get a lot of reports and the more info you give us, the more likely we'll be able to address it in a timely fashion.

Please [read the contributing guidelines](https://github.com/masayuki0812/c3/blob/master/CONTRIBUTING.md), then add the following information to your issue:

- [ ] Operating system and web browser (with version)
- [ ] What version of the library
- [ ] Ideally, a [JSFiddle](https://jsfiddle.net/) example depicting the specific problem really helps us out. [Use this template](https://jsfiddle.net/aendrew/L4ocdkcq/) for issues with 0.4.11-rc4!
- [ ] If you were doing anything unusual, like using C3 in conjunction with a particular library or framework

Thank you for your cooperation — we rely on users like you to help make C3 the best charting library it can be!
