### ISSUE TITLE
Request: Possibility to pan without enabling Zoom.

### ISSUE THREAD

**Issue by mirowane** [masayuki0812/c3#1600]
I set an extent for my chart. And I would like to be able to pan through the rest of the chart without having to enable zooming.
Is there a way to achieve it?

**Comment by aendrew** [comment]
Hi there! We try to keep the issue queue clear for specific code-related problems with C3, could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3) instead? Thank you!
