### ISSUE TITLE
On click event is only for data declaration (c3.render) not for each data.load 

### ISSUE THREAD

**Issue by rosorrentino** [masayuki0812/c3#1605]
Hi 

I was wondering if it’s possible to set onclick event based on data.load

I have 2 different functions to generate the chart and then get the data dynamically, my data has more information than the chart uses, so my array for data.load is only part of all data, I want to use the other part of this dynamic data in a on click event. 

But  I can only use it during c3.generate, data declaration.

**Comment by rosorrentino** [comment]
I guess my solution would be to make part of this data “global” (not big fan) and use on.click event to load a 3rd function that will use this data.

**Comment by aendrew** [comment]
Hi there! We try to keep the issue queue clear for specific code-related problems with C3, could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3) instead? Thank you!
