### ISSUE TITLE
Change the color of the tick labels differently

### ISSUE THREAD

**Issue by ManssonMarcus** [masayuki0812/c3#1606]
Hi!

Is there a way to change the color of the tick(label) separately? I would like to have som ticks(labels) in white and some in another color. 
![skarmavbild 2016-02-29 kl 15 06 52](https://cloud.githubusercontent.com/assets/6939011/13396701/5e5edbaa-def6-11e5-8a14-f0b23af7804a.PNG)

It would be awesome if there was a way to add a id to each tick!

**Comment by aendrew** [comment]
Hi there! We try to keep the issue queue clear for specific code-related problems with C3, could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3) instead? Thank you!

(Also, try changing `.c3-axis .tick line` using CSS...)
