### ISSUE TITLE
Ticks data missing on zoom

### ISSUE THREAD

**Issue by anudeepshetty17** [masayuki0812/c3#1607]
I have problem while implementing c3 when zoom or brush(subchart) the ticks should auto calculate the domains and get updated. but with c3 the ticks remain blank on zoom. 

Also is there any way to specify the intervals for x axis in c3.?
![capture](https://cloud.githubusercontent.com/assets/6776673/13397746/443eecb0-dec9-11e5-88da-2cb64acb985b.PNG)

**Comment by aendrew** [comment]
It's quite possible that could be a bug, but it's really hard to verify it without more information. We get a lot of reports and the more info you give us, the more likely we'll be able to address it in a timely fashion.

Please [read the contributing guidelines](https://github.com/masayuki0812/c3/blob/master/CONTRIBUTING.md), then add the following information to your issue:

- [ ] Operating system and web browser (with version)
- [ ] What version of the library
- [ ] Ideally, a [JSFiddle](https://jsfiddle.net/) example depicting the specific problem really helps us out. [Use this template](https://jsfiddle.net/aendrew/L4ocdkcq/) for issues with 0.4.11-rc4!
- [ ] If you were doing anything unusual, like using C3 in conjunction with a particular library or framework

Thank you for your cooperation — we rely on users like you to help make C3 the best charting library it can be!
