### ISSUE TITLE
Loading json data can't show in c3js chart

### ISSUE THREAD

**Issue by ThuraMoe** [masayuki0812/c3#1609]
I have four legend in my chart such as 'dept1','dept2','dept3','dept4'. 

The main point what I want is, when I click 'dept1' legend, I want to load new data called 'SMV' into my chart.

Here is the code for chart.

```
chart = c3.generate({
				bindto: '#chart',
				data: {
					x: 'date',
					xFormat: '%Y-%m-%d',
					json:<?php echo json_encode($multi_data);?>,
					keys: {
						x: 'date',
			            value:	<?php echo json_encode($deptName)?>//['dept1','dept2','dept3','dept4']
					}, 
					type: 'line',
				},
				legend: {
					position: 'right',
					item: {
						onclick: function (d) { 
								console.log("onclick", d); 
								detail_report(d);
							}
						}
				},
				axis: {
					x: {
						type: 'timeseries',
						tick:{
							format: m_y_format,
							rotate: 75,
						},	
                      }
           }
			});
```
The `detail_report()` function is used to get `SMV` data of each legend(Department) by using ajax. Here is the code:
```
function detail_report(d) {
			$.ajax({
				url: 'detail.php',
				type: 'post',
				data: {deptname:d},
				dataType: 'json',
				success: function(data) {
					console.log("success");
					var temp = "";
					if(data && data!="") {
						//console.log(JSON.stringify(data.total));
						//console.log(data.dept_smv);
						var smv_data = data.dept_smv;
						console.log(smv_data);
						show_smv(smv_data);
                                //.....other code
					}
				},
				error: function() {
					console.log("error");
				}
			});
			return true;
		}
```
In my detail.php, I calculate `SMV` data for each department and send back by json encode like this.
```

$query = "...";	
$dept_smv = get_data($query);

function get_data($sql) {
	$date = array();
	$percent =  array();
	$rsl = array();
	.......
	.......
	//query to get date, dept_name, percent, moving_avg array etc.
	.......
	$rsl = "{'date':".json_encode($date).",'".$dept_name."':". json_encode($percent_arr).",'SMV':".json_encode($moving_avg)."}";
	return $rsl;
}

$total[] = ......; //other array not related dept_smv

echo json_encode(array('total'=>$total,'dept_smv'=>$dept_smv));
```
The `dept_smv` get from ajax is like this,
`{'date':["2015-11-17","2015-11-23","2015-11-24","2015-11-25","2015-11-26","2015-11-27","2015-11-28","2015-11-29","2015-11-30","2015-12-01","2015-12-02","2015-12-03","2015-12-04","2015-12-05","2015-12-06","2015-12-07","2015-12-08","2015-12-09","2015-12-10","2015-12-11","2015-12-12","2015-12-13","2015-12-14","2015-12-15","2015-12-16","2015-12-17","2015-12-18","2015-12-19","2015-12-20","2015-12-21","2015-12-22","2015-12-23","2015-12-24","2015-12-25","2015-12-26","2015-12-27","2015-12-28","2015-12-29","2015-12-30","2015-12-31","2016-01-01","2016-01-02","2016-01-03","2016-01-04","2016-01-05","2016-01-06","2016-01-07","2016-01-08","2016-01-09","2016-01-10","2016-01-11","2016-01-12","2016-01-13","2016-01-14","2016-01-15","2016-01-16","2016-01-17","2016-01-18","2016-01-19","2016-01-20","2016-01-21","2016-01-22","2016-01-23","2016-01-24","2016-01-25","2016-01-26","2016-01-27","2016-01-28","2016-01-29","2016-01-30","2016-01-31","2016-02-01","2016-02-02","2016-02-03","2016-02-04","2016-02-05","2016-02-06","2016-02-07","2016-02-08","2016-02-09","2016-02-10","2016-02-11","2016-02-12","2016-02-14","2016-02-15","2016-02-16","2016-02-18"],'dept1':["0.00","71.43","66.67","67.44","73.17","65.85","87.50","81.82","64.29","64.29","69.77","72.09","73.17","60.00","83.33","75.00","75.61","63.41","78.95","68.29","76.92","63.64","82.50","66.67","61.90","60.94","70.37","58.33","66.67","73.81","74.42","73.81","66.67","76.19","78.57","33.33","53.85","65.79","80.56","77.78","42.86","25.00","83.33","55.26","69.77","75.00","60.00","80.49","76.92","60.00","65.91","66.67","78.57","60.47","65.85","47.37","42.86","60.00","62.79","75.00","55.00","65.85","68.75","85.71","53.66","78.05","78.57","83.33","61.90","70.37","75.00","66.67","67.50","63.16","62.86","71.79","43.75","42.86","72.22","0.00","50.00","100.00","100.00","0.00","0.00","0.00","0.00"],'SMV':[null,null,null,null,null,null,null,73.411428571429,72.391428571429,72.051428571429,72.384285714286,72.23,73.275714285714,69.347142857143,69.562857142857,71.092857142857,72.71,71.801428571429,72.781428571429,72.084285714286,74.501428571429,71.688571428571,72.76,71.482857142857,71.267142857143,68.694285714286,68.991428571429,66.335714285714,66.768571428571,65.527142857143,66.634285714286,68.335714285714,69.154285714286,69.985714285714,72.877142857143,68.114285714286,65.262857142857,64.03,64.994285714286,66.581428571429,61.82,54.167142857143,61.31,61.511428571429,62.08,61.285714285714,58.745714285714,64.121428571429,71.538571428571,68.205714285714,69.727142857143,69.284285714286,69.794285714286,69.861428571429,67.77,63.548571428571,61.1,60.255714285714,59.701428571429,59.191428571429,58.41,58.41,61.464285714286,67.585714285714,66.68,68.86,69.37,73.417142857143,72.852857142857,73.084285714286,71.554285714286,73.412857142857,71.905714285714,69.704285714286,66.78,68.192857142857,64.39,59.798571428571,60.591428571429,50.948571428571,49.068571428571,54.374285714286,58.404285714286,52.154285714286,46.031428571429,35.714285714286,35.714285714286]}`

I use `show_smv()` function to show `SMV` data. But that data(SMV) are not rendered in chart and I don't get any error. Here is my `show_smv()` function,
```
function show_smv(smv_data) {
			console.log(smv_data);//argument are came form dept_smv data of detail_report() function
			chart.load({
				bindto:'#chart',
				data: {
					x: 'date',
					xFormat: '%Y-%m-%d',
					json: smv_data,
					keys: {
						x: 'date',
						value: <?php echo json_encode($dept_smv);?>,['dept1','dept2','dept3','dept4','SMV']
					},
					type:'line' 
				},
				axis: {
					x: {
						type: 'timeseries',
						tick:{
							format: '%Y-%m-%d',
							rotate: 75,
						},					
						label: {
							text: 'Date',
							position: 'outer-center',
						},
						height: 100,
					}
                               }
			});
		}
```
I don't know which part is wrong in my code. I'm appreciate for any suggestion.

**Comment by aendrew** [comment]
Hi there! We try to keep the issue queue clear for specific code-related problems with C3, could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3) instead? Thank you!
