### ISSUE TITLE
Tooltip doesn't work with little bottom values

### ISSUE THREAD

**Issue by YvonneSpitznagel** [masayuki0812/c3#1611]
Hello,
if I have a stacked bar value with 3 values and the lowest value is very little the tooltip doesn't show. It shows only the tooltip for the brass value.
Any ideas?

**Comment by aendrew** [comment]
Hi there! We try to keep the issue queue clear for specific code-related problems with C3, could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3) instead? Thank you!
