### ISSUE TITLE
In line chart, data color and data colors do not works in same time.

### ISSUE THREAD

**Issue by say8425** [masayuki0812/c3#1612]
http://jsfiddle.net/say8425/mmam4jLw/3/

I want to colorize the specify point in line chart.
So I use `data color`. And it works.
But `data colors` is disabled. So line color is changed to black.

Is it bug or my mistake?

**Comment by say8425** [comment]
http://jsfiddle.net/say8425/tduknz24/
Sorry I solve it with [this guide](http://c3js.org/samples/api_data_color.html)
Please close this issue.

**Comment by aendrew** [comment]
Glad you were able to solve it. 😄
