### ISSUE TITLE
i dont know how to generate c3 charts into plot image(png) ???

### ISSUE THREAD

**Issue by adrianf29** [masayuki0812/c3#1613]
i dont know how to generate c3 charts into plot image(png) ???pleaseee!

**Comment by ndabAP** [comment]
https://github.com/masayuki0812/c3/issues/313

And:

http://stackoverflow.com/questions/32122145/transforming-svg-to-canvas-png-and-jpeg-with-c3-js

**Comment by adrianf29** [comment]
hi @ndabAP  thanks for your reference...


but can you help me how to put it..

this is my code



<script>
	var mmchart = c3.generate({
    bindto: '#bar_chart_stack_<?php echo $kode_pie?>',
    padding:{
        left: 30,
        right: 15
    },
    data: {
        x: 'x',
        columns: <?php echo $bar_data_new?>,
        type: 'bar',
        groups: [
            ['Positive','Neutral', 'Negative']
        ],
        order: null,
        label: true,
        onclick: function(e) { 
            var obj1 =  "<?php echo $ticks?>";
            var obj2 =  obj1.split(",");
            var idx  =  obj2[e.index];
                idx  =  idx.replace("'","");
                idx  =  idx.replace("'","");
            //console.log(e); 
            <?php if($kode_pie=='018') { ?>
             get_detail_subcli('tanggal_2', idx, e.id);
            <?php } ?>
             <?php if($kode_pie=='019') { ?>
             get_detail_subcli('client', idx, e.id);
            <?php } ?>
             <?php if($kode_pie=='050') { ?>
             get_detail_subcli('media', idx, e.id);
            <?php } ?>
        }
    },
    axis: {
        x: {
            type: 'category',
            tick: {
                rotate: 15,
                multiline: false
            },
            height: 0,
        }
    },
    bar: {
        width: {
            ratio: 0.5
        }
    },
    tooltip: {
        format: {
            title: function (d) {
                //return 'Data ' + d;
                var tooltiptitle = [<?php echo $ticks ?>];

                return tooltiptitle[d];
            },
            value: function (value, ratio, id) {
                return value;
                // var format = id === 'data1' ? d3.format(',') : d3.format('$');
                // return format(value);
            }
        }
    }
});

mmchart.data.colors({
    Positive: '#30A640',
    Negative: '#D8655A',
    Neutral: '#9AB6E6'
});
	</script>
<body>
<div id="bar_chart_stack_<?php echo $kode_pie?>" style="height: 220px;"></div></body>


please help me how to create a button to export that chart to png.. cause i need the base64 image after export. big thanks to you @ndabAP

**Comment by aendrew** [comment]
Hi there! We try to keep the issue queue clear for specific code-related problems with C3, could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3) instead? Thank you!
