### ISSUE TITLE
C3.js uses Object.observe() which is deprecated and will be removed soon in Chrome

### ISSUE THREAD

**Issue by lbayerl** [masayuki0812/c3#1614]
In function c3_chart_internal_fn.observeInserted .observe() is used which will be removed soon in Chrome (50): see [link](https://www.chromestatus.com/features/6147094632988672)

**Comment by aendrew** [comment]
@lbayerl Yikes, that will be bad. cc: @masayuki0812, we need to either polyfill or change that ASAP.

**Comment by alleyj** [comment]
@aendrew Unless I'm misreading the code, it is using the observe function of a MutationObserver which is different than Object.observe.

MutationObserver: https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver

**Comment by aendrew** [comment]
@alleyj Ah! Right you are, I should've investigated a bit further. Thanks!

Closing as `invalid`.

**Comment by lbayerl** [comment]
Sorry, should have seen this as well :-(

**Comment by alleymae** [comment]
@alleyj.. Yes it was bug on my phone that u used.  Been trying to find out what that was..  Facebook status
