### ISSUE TITLE
i just want the column names in x-axis so pls suggest me how to do? is it possible to add column name using c3.js?

### ISSUE THREAD

**Issue by rajeshtsc09** [masayuki0812/c3#1619]
this is my csv file.
player,Score,strikeRate
a,10,12	
1,12,34
b,14,7.86	
c,13,7.19	
g,14,7.08	
f,19,7.53	
e,11,7.17	
d,97,7.65	
this is my csv file...
my output
![op1](https://cloud.githubusercontent.com/assets/16222562/13668229/836628b6-e6e1-11e5-8d35-5f1600da68c7.PNG)
but I wants to display player column in x axis.

**Comment by rajeshtsc09** [comment]
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="c3.css">
  </head>
  <body>
    <div id="chart"></div>

    <script src="d3.min.js" charset="utf-8"></script>
    <script src="c3.min.js"></script>
    <script>
var chart = c3.generate({
    data: {
        url: 'cdc_female_hcageinf.csv',
        type: 'bar'

        },
    tooltip: {
        show: true
    },
            point: {
        show: true
    }
    
});
</script>
</body>
</html>

**Comment by aendrew** [comment]
Hi there! We try to keep the issue queue clear for specific code-related problems with C3, could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3) instead? Thank you!
