### ISSUE TITLE
A bar chart to represent percentage values out of 100%

### ISSUE THREAD

**Issue by tadkaliszewski** [masayuki0812/c3#1624]
Great library. Thanks!

Sorry if this is obvious or has been answered already. I can't achieve something that is simple I think.

I have a simple bar chart on which I need to show bars with values between 0 to 100 (100%). I would like the chart to always show 100 tick. However ticks are shown only up-to maximum bar's value. So I'd say it is scaling the chart to only available values. In the example below it only shows 60 tick but I need the axis to still go up to 100 to show that the bar lacks 40% because there is 100% potentially.

I was expecting this should be as easy as explicitly setting tick.values but it does not work as I imagined it would.

Please help.

var c1seriesData = {"Categories":["Present","Approved Educational Activity","Authorised Absence","Unauthorised Absence","Unexplained Absence","Missing"],"data1":[59.05,0,19.4,20.26,13.36,1.29]};
               
var c1seriesNames = {"data1":"Attendance Marks"};

                var c1chart = c3.generate({
                   
                    data: { x : 'Categories',
                        json: c1seriesData,
                        types: {
                            data1: 'bar'
                        },
                        colors: {data1: "#5b9bd5"}
                    },
                    axis: {
                        rotated: true,
                        x: {
                            type: 'category'
                        },
                        y: {
                            label: {
                                text: '',
                                position: 'outer-middle'
                            },
                            //tick: { count: 11, values: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100] }
                            tick: { culling: false,
                                values: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]  }
                        }
                    }
                    ,tooltip: { format:{
                        //title: function (d) {  }
                        value: function (value, ratio, id) {
                            //var format = id === 'data1' ? d3.format(',') : d3.format('$');
                            return value + "%";
                        }
                    } }
                });
                c1chart.data.names(c1seriesNames);

**Comment by aendrew** [comment]
Hi there! We try to keep the issue queue clear for specific code-related problems with C3, could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3) instead? You'll probably get a faster response as well. Thank you!
