### ISSUE TITLE
"Tooltip" is not displayed in Bar chart with latest version of chrome

### ISSUE THREAD

**Issue by dmb1987** [masayuki0812/c3#1630]
Hi , a got error "Uncaught TypeError: Cannot read property 'getItem' of undefined " when the mouse is over each bar.

Is only with chrome ,in firefox working properly.

Any help? Thanks.

**Comment by Sofiane000** [comment]
This is the function where there is an issue : c3_chart_internal_fn.isWithinBar
that.pathSegList is undefined

**Comment by panthony** [comment]
See #1566

**Comment by dmb1987** [comment]
Thanks pantonhy! solved with dev-branch
