### ISSUE TITLE
No carga Chart.load en multiples graficos en una pagina

### ISSUE THREAD

**Issue by AlexisReb** [masayuki0812/c3#1634]
Hola a todos,

Tengo varios gráficos en una pagina los cuales quiero cargar a través del método load al hacer consulta a la base de datos con una repuesta json, de los 5 gráficos, que son iguales, la diferencia es cual es el array que cargo de la respuesta json que es multidimensional.

chart1 = c3.generate({
  bindto : "#grafico1",
  data : {
    type : 'bar',
    columns : chartData1
  }
});

chart2 = c3.generate({
  bindto : "#grafico2",
  data : {
    type : 'bar',
    columns : chartData2
  }
});

chart3 = c3.generate({
  bindto : "#grafico3",
  data : {
    type : 'bar',
    columns : chartData3
  }
});

chart4 = c3.generate({
  bindto : "#grafico4",
  data : {
    type : 'bar',
    columns : chartData4
  }
});

chart5 = c3.generate({
  bindto : "#grafico5",
  data : {
    type : 'bar',
    columns : chartData5
  }
});

Después de recibir la respuesta json cargo los array y los paso al gráfico así

chart1.load({
              columns : chartData1
            });

Para cargar los array uso lo siguiente:

 chartData1.push(array1);

Esto dos pasos para cada uno de los gráficos, pero solo me muestra el segundo gráfico, la verdad ya me estoy volviendo loco buscando y revisando el código una y otra vez. en una de las respuestas hacen esto:

$('#grafico1').append(chart1.element);

Sacando el bindto al generar el gráfico, y haciendo después la declaración, pero a mi no me ha funcionado. Desde ya cualquier ayuda que me sirva para solucionar o ir aclarando el error, lo agradezco.

Saludos.

**Comment by AlexisReb** [comment]
Estimados,

Olvidenlo, estaba yo cometiendo un error al cargar los array.

Gracias

**Comment by aendrew** [comment]
Gracis @AlexisReb!
