### ISSUE TITLE
Question: how to disable vertical line on hover

### ISSUE THREAD

**Issue by unlight** [masayuki0812/c3#1646]
When I moving mouse along Y axis.
In addition to tooltip, vertical line is showing.
How to disable it?

Example here http://c3js.org/samples/simple_multiple.html

**Comment by abacaj** [comment]
Use css:

`.c3-event-rects { display: none }`

**Comment by aendrew** [comment]
Thanks for answering @abacaj!
Closing as resolved.

**Comment by pashog** [comment]
> Use css:
>
> .c3-event-rects { display: none }

This is an incorrect solution. Because in this way you'll hide entire events layer.
If you need to disable only vertical bar, use **.c3-xgrid-focus** class:

`.c3-xgrid-focus {
    display: none;
}`
