### ISSUE TITLE
Line and legend coloring seems not to sync, Coloring depending on data names

### ISSUE THREAD

**Issue by Jax89** [masayuki0812/c3#1653]
Hi,
I try to code a function that will create a line chart. The problem ist, that the data for the function varies (and the IDs are given by a list) and can consist two kinds of data with different IDs and their number also varies. The coloring should change depending on which data it contains (given by a start letter). Charting itself works just fine. But for some reason, after using the color function, the legend is black (or the lines, depending on if I use "d" or "id" in the function. What am I missing? Do I need to use two functions, and if so, how?
```
var chart_here = function generate_chart(data, binder){
var chart = c3.generate({
    bindto: binder,            
            data: {
                json:data,
                keys: {x:"x",
                        value:value_names,
                  },
        type: 'line',            
        color:
            function (color, d) {            
            name=d.id;         
            if (name.startsWith('X')){return "#0000FF";} else if (name.startsWith('Y')){return "#d00";}},
            }, 
        axis:{ 
...more code
```

**Comment by aendrew** [comment]
Hi there @Jax89! We try to keep the issue queue clear for specific code-related problems with C3, could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

If you think it's a genuine bug, please create an example JSFiddle. Thank you!
