### ISSUE TITLE
Avoid y.tick captions like 2.3333333

### ISSUE THREAD

**Issue by BlaM** [masayuki0812/c3#1654]
How do I avoid captions like these:

![image](https://cloud.githubusercontent.com/assets/176011/14534462/95a64dbe-0269-11e6-8d75-41a729f30e16.png)

 - I don't know the maximum value (updated in real time)
 - I need to limit the number of ticks because of very limited height

Obviously this does not work:

        axis: {
            y: {
                tick: {
                    count: 4,
                    culling: 4
                },
                min: 0
            }
        },

Also note the -0.2 while axis.y.min = 0

**Comment by Dekai** [comment]
Maybe could try 
tick: {
      values: [0, 0.6, 1,4, 2]
}

The array [0, 0.6, 1,4, 2] could be generate in real time based on your random max value. Say min is 0, your max 12. You want 4 tick, so write some code to pick values from 0 to 12.

**Comment by BlaM** [comment]
I switched to flotcharts - but maybe a solution to that problem might be helpful to others.

**Comment by kjavia** [comment]
There is a `tick.format` which takes a function, including d3.format strings to solve this problem.
http://c3js.org/reference.html#axis-x-tick-format

**Comment by BlaM** [comment]
I'm working with integers as input values, so ending up with ticks at non-integer positions will not help as much as I'd like - but that tick.format being a function may be a hint into the correct direction. 

Maybe having an option to use a function(min, max) for tick.count would be a good idea to solve this kind of problem. That would allow me to set the count dynamically to - for example - 2 if I only have values between 0 and 2.

**Comment by aendrew** [comment]
Yep, tick.format is your friend in this instance. Closing as question (Thanks for answering @kjavia!).
