### ISSUE TITLE
Create C3 js charts from chart metadata stored as strings

### ISSUE THREAD

**Issue by FarhanSaleem** [masayuki0812/c3#1655]
Hi, 
  I am building a prototype of an online report which could possibly have multiple charts in it. I have created a json structure in which i have all the charts under a report object. I had to store it as a string in the object. It is the "META" property in the report.json file. When I load the page i want to get the object and create as many chart objects are in the report. but I am having a hard time trying to Parse the metadata object back to JSON. I have built a plunker to showcase the issue. The html page is already generating the divs for the charts to be plugged into... can someone please show me how to convert the metadata string to a JSON object so i can pass it into a c3.generate(item[i].META) function. Please look at the plunk below. Please let me know of a good way to create the charts.

[c3 plunk](https://plnkr.co/edit/EqfAdF028tE97LlKmzv0?p=preview)

In case you are wondering the json is valid. I have a commented out copy of the same json i tested to verify it created a chart.

**Comment by aendrew** [comment]
It's invalid JSON. Paste the string in `chartMetaData` into [JSONLint](http://jsonlint.com/). You need to enclose all key-value pairs with double-quotes.

Regardless, the issue queue isn't the place to ask this. We try to keep the issue queue clear for specific code-related problems with C3, could you please ask future questions on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3) instead? Thanks.
