### ISSUE TITLE
Stacked Bar Chart with grouped and stacked columns, without summing

### ISSUE THREAD

**Issue by scottjason** [masayuki0812/c3#1656]
I have a stacked bar as in the c3 examples but need the values not to be summed.

My use case is exactly this from HighCharts:

http://www.highcharts.com/demo/column-stacked-and-grouped/grid-light

In the above example, the values in the bars are not causing the y-axis to be a sum of the two.

Is this possible with c3?

**Comment by galiganu** [comment]
Hi - is there a way to do this? (not to sum the values of a group)

Thanks!

**Comment by n2lose** [comment]
I think just using d3js to do that, [example](http://jsfiddle.net/Dimmy/xey6xuf2/2/)
