### ISSUE TITLE
Brush Auto Adjustment

### ISSUE THREAD

**Issue by vprasad0821** [masayuki0812/c3#1657]
Hi,
I have built a bar chart where i display quarter data of a particular year, on load of the chart am displaying the previous 4 quarters from the current quarter that is the last tick in the x-axis, am able to achieve this using subchart where i set extent:[data.length - 4, data.length] eg: extent[2,6]. which shows 4 quarters but when the brush is at the extreme right and when brush is clicked it adjusts automatically by increasing the brush width this is causing problem for me since i feed data to the chart on various options and whenever i change the options it keeps increasing the width on click of the brush. but this is not the case when the brush is on the mid ticks of the x-axis. Is their a way to stop the auto adjustment of the brush?if yes please suggest.

fiddle link: https://jsfiddle.net/vprasad2108/njqr2anc/8/   (This example gives you an abstract of the problem)

**Comment by kjavia** [comment]
So you are changing the data after the chart it initially rendered? If so the brush may not be getting applied. You can use chart.zoom([x_axis_start, x_axis_end]) to re-apply or adjust the brush, after the chart is drawn.

**Comment by vprasad0821** [comment]
Thank you for the solution, yes i am changing the data after the chart is initially rendered, as you suggested i used chart.zoom([x_axis_start, x_axis_end]) and its setting the brush to exact 4 quarters but when i click on the brush it expands and adjusts itself to fit the ticks. how can we avoid it?

**Comment by kjavia** [comment]
That's how brush functions. If you click on or around the brush in the context chart, it will change.

**Comment by vprasad2108** [comment]
Thank you if i come out with something where i can avoid it i will put it up here.

**Comment by aendrew** [comment]
What @kjavia said (thanks for handling that btw! :smile:). Closing as invalid.
