### ISSUE TITLE
Can anyone tell me, is it possible to customise this plugin like below diagram

### ISSUE THREAD

**Issue by Thilak8654** [masayuki0812/c3#1661]
is it possible to customise this plugin like below diagram, if yes can anyone tell me how
![customise](https://cloud.githubusercontent.com/assets/8691866/14667183/844e14a2-06fb-11e6-938f-373255b45282.png)

**Comment by lflores** [comment]
Hi @Thilak8654 You can use [color-pattern](http://c3js.org/reference.html#color-pattern) property to configure your own scale of colors, as you can see on this [example](http://c3js.org/samples/options_color.html). Also c3 support styling by css and you can change some of properties, changing css classes. Some reference of used classes[here](http://c3js.org/reference.html#class-c3-chart-bar).

**Comment by Thilak8654** [comment]
Thanks for your response. But how to add 3 side data as in the figure above.

**Comment by aendrew** [comment]
@Thilak8654 This isn't really the place to ask — please use the Google Group or Gitter. Thanks.
