### ISSUE TITLE
Bar chart onclick not fired when there are many columns (~4000)

### ISSUE THREAD

**Issue by Avien** [masayuki0812/c3#1665]
I am familiar with issue #1566 
I have installed c3#dev branch
The onClick works for simple bar charts
But when there are too many columns it does even fire

Thanks

**Comment by vprasad0821** [comment]
Even i face the same issue, some times it it works fine and some times it doesn't even trigger onClick event. I wasted a lot of time by not knowing this is a library issue,  not sure of what to do with this issue.

**Comment by Avien** [comment]
I suspect its a d3 issue, since in the c3 source the configuration binds the onclick event properly, but d3 listeners are not fired

**Comment by kjavia** [comment]
Does your console show any errors when you click?

**Comment by vprasad2108** [comment]
No it doesn't show any error when clicked basically it doesn't trigger onClick function.

**Comment by aendrew** [comment]
@Avien It really helps in these instances if you post a working JSFiddle demonstrating the bug. Otherwise maintainers really have nothing to go on. Simply saying "it has 4000 rows!" isn't really adequate — what browser are you even using?

Closing until I have more info.
