### ISSUE TITLE
Add config for stroke

### ISSUE THREAD

**Issue by neilime** [masayuki0812/c3#1666]
Hi,

It will be useful to allows stroke configuration. Example :
```json
var chart = c3.generate({
    "stroke": "#FEF",
    "donut":{}
});
```

**Comment by aendrew** [comment]
The general principle of the library is that this is done via CSS. Also, that's way too vague to be useful — what stroke in the chart does that refer to?

Closing for now, please provide more detail. Thanks! :smile:
