### ISSUE TITLE
Log scale when data input coming from a URL ?

### ISSUE THREAD

**Issue by HornKild** [masayuki0812/c3#1667]
Hello,

I'm trying to makes possible having a log scale with my data input coming from a URL (csv file).
What would be the right workarount to achieve this ? I'm not very familiar with JS, could you please help me customizing this piece of code ?

Regards,

Florent 

```
data_test_original = ['data1', 10, 100, 1000, 3, 500, 50, 5, 3000]
data_test = ['data1'];
for(var i=1; i<data_test_original.length; i++){
    data_test[i] = Math.log(data_test_original[i]) / Math.LN10;
}
var chart_test = c3.generate({
    bindto: '#chart_test',
    size: {
        height: 240,
        width: 480
    },
    data: {
      columns: [
        data_test
      ]
    },
    axis : {
        y : {
            tick: {
               format: function (d) { return Math.pow(10,d).toFixed(2); }
            }
        }
    },
});
```

**Comment by aendrew** [comment]
Hi there! We try to keep the issue queue clear for specific code-related problems with C3, could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3) instead? Thank you!
