### ISSUE TITLE
New option to change the position of the axes

### ISSUE THREAD

**Issue by fmichael** [masayuki0812/c3#261]
With the legend position having the option to be switchable between the bottom and right side of the screen it would also be very useful to have an option to toggle the position of the axis(s). Mainly that of the x axis being able to appear above or below the chart. Having the ability to toggle the y axis left or right of the chart is also useful but less so since you have the option to add a second y axis. Adding the option to the x axis allows for more room at the bottom for a legend and a less cluttered look between having a zoom option appearing below as well as a legend and the axis. 

Hopefully this is a simple enough idea to implement, Thanks in advance.

**Comment by aendrew** [comment]
Apologies, I didn't realise this issue existed before creating #895; alas, I've done a bit of work referencing the newer issue. 

Closing this and marking as duplicate; can we please move discussion about axis positioning to the other issue? Thanks!

**Comment by sipolyashhivangi** [comment]
Hi,
How can I change the position of y axis from left to right in c3?

Any will be appreciated.
