### ISSUE TITLE
Add a configuration option for spline interpolation style

### ISSUE THREAD

**Issue by rzds** [masayuki0812/c3#479]
There's no value smaller than 0 and still the line goes under it. Any fixes for this ?
![hh](https://cloud.githubusercontent.com/assets/1256878/3812428/1c563376-1caa-11e4-8a70-b8b92760285b.png)

**Comment by mortenbo** [comment]
Sorry to comment on an closed issue but I was scratching my head over this as well.

I investigated the c3 code and saw that the method `c3_chart_internal_fn.getInterpolate` uses a cardinal interpolation option for splines. Would it make sense to use the `monotone` option instead or allow for customization to avoid forking the repo or overwriting the method?

See [this](http://www.d3noob.org/2013/01/smoothing-out-lines-in-d3js.html) for more information.

Thank you for an amazing library.

**Comment by aendrew** [comment]
@mortenbo That's a good point; tbh, given `spline` doesn't have any configurable options, maybe it should be merged into the `line` chart and that chart style given a configurable interpolation option?

Reopening and renaming to better reflect issue.

**Comment by mortenbo** [comment]
A configurable interpolation option would suit me very well.

**Comment by edmundoa** [comment]
Hi,

I am also interested in adding a configuration option to set the interpolation type in a spline, and willing to do a PR with the required changes. Reading this issue I assume you would like to have that option in the library, but I'm asking anyway :)

**Comment by mortenbo** [comment]
Awesome. Much appreciated :-)
