### ISSUE TITLE
Genarating Pie chart

### ISSUE THREAD

**Issue by nitinuttarwar** [masayuki0812/c3#484]
I have Json data like this: 
[{\"candidate\":\"Mark D. Obenshain\",\"votes\":98963},{\"candidate\":\"Mark R. Herring\",\"votes\":157550},{\"candidate\":\"Ken T. Cuccinelli, II\",\"votes\":93256},{\"candidate\":\"Robert C. Sarvis\",\"votes\":13746},{\"candidate\":\"Terry R. McAuliffe\",\"votes\":152049},{\"candidate\":\"E.W. Jackson\",\"votes\":91143},{\"candidate\":\"Ralph S. Northam\",\"votes\":164236}]

Can i plot the pie chart using C3

**Comment by agdev** [comment]
Hi,
I have similar need, json data with two columns datalabel and value.
I think pie chart should work as other charts and not to be exception.
