### ISSUE TITLE
printing issue with IE

### ISSUE THREAD

**Issue by yoocos** [masayuki0812/c3#503]
Hi,
I have built an application to play with the statistics of first names in Switzerland. 
You can see the application here :  http://d39m457qtmvvho.cloudfront.net/vornamen/index.html

My issue is the following (and very strange),
in the first tab (called "Vornamen"), look for any name (let's say David) and perform a search.
Everything displays fine.

Then click on the print icon. You will have a new page opening (it is basically the same page but with parameters in the URL to say it has to be printed).

Everything loaded and displayed just fine. Click again on the button to print the page.

Now the graph does not print well. 
It is the first time I see something like this. Everything displays fine but when you try to print it the layout goes bezerk. It only happens on IE ( tried on 9-10 and 11) but everything is fine on Chrome and Firefox.

I don't even know how to debug this. Can you guys help me with that? Do you have any idea ?

Thank you so much in advance

**Comment by masayuki0812** [comment]
Can you ask Google Group again? https://groups.google.com/forum/#!forum/c3js
And please let me close at the moment.
