### ISSUE TITLE
chart with flipped min-max values for y axis is cut off 

### ISSUE THREAD

**Issue by yuvii** [masayuki0812/c3#534]
If you set up the y axis `min` and `max` values to be flipped (i.e., min is higher than max, a common need if, for example, you're showing data where less is better), the chart is calculated wrong and the graph is cut off. [See demo](http://jsfiddle.net/yuvii/Lqke63qt/)

    var chart = c3.generate({
        data: {
            columns: [
                ['data1', 100, 200, 150, 300, 200],
                ['data2', 400, 500, 250, 700, 300], ]
        },
        axis: {
            y: {
                min: 700,
                max: 100
            }
        }
    });

I can achieve this with some trickery (using [negative values and formatting](http://jsfiddle.net/yuvii/Lqke63qt/3/)), but I'm considering that a hack

**Comment by masayuki0812** [comment]
I added `axis.y.inverted` and `axis.y2.inverted` option by this commit, so now we can invert easily by setting this option `true`.
I'll release this in the next version v0.4.9 shortly. Thanks.

**Comment by masayuki0812** [comment]
v0.4.9 has been released, so please let me close.

**Comment by aendrew** [comment]
Cool! Adding documentation tag.

**Comment by spongeboy** [comment]
Updated demo to use new inverted property. Note that the min and max need to be changed back so that min less than max.

http://jsfiddle.net/5uxf0bqc/
