### ISSUE TITLE
Loading json for multiple data lines timeseries chart

### ISSUE THREAD

**Issue by JiaJian** [masayuki0812/c3#563]
Hey there!

I was wondering if it's possible to load json data to create a chart with multiple data lines with its x-axis as a timeseries?

I used this example here (see https://groups.google.com/d/msg/c3js/UDQB8JorDho/up0gSEQQavUJ) but I realise the json parser is still severely limited to only certain formats, tried to crawl the Interwebs for examples but no luck. Was wondering if there are any workarounds?

Thanks! :)

**Comment by keyscores** [comment]
This still seems broken in the jsfiddle above, with the latest master code. http://jsfiddle.net/7kYJu/424/

**Comment by aendrew** [comment]
@keyscores Huh, right you are. Reopening...

**Comment by ianjennings** [comment]
@aendrew @keyscores 

I modified that JSFiddle to use the syntax as suggested by @masayuki0812 in #516 and it renders properly.

http://jsfiddle.net/7kYJu/1940/

You can probably close this.

**Comment by aendrew** [comment]
@ianjennings Thanks for reporting back!

Closing as resolved.
