### ISSUE TITLE
mouseout happens (and fails) even though chart is already destroyed

### ISSUE THREAD

**Issue by sdahlbac** [masayuki0812/c3#618]
Steps to reproduce:
- render chart
- move mouse over bar
- call chart.destroy() e.g. using timeout
- move mouse
- on('mouseout' is called  - and fails on following line:

        (targets || $$.data.targets).forEach(function (t) {

(both targets and $$.data.targets are undefined) - but for a destroyed chart - why is it even happening in the first place?

c3_chart_internal_fn.hasType (c3-0.3.0.js:2971)
c3_chart_internal_fn.hasArcType (c3-0.3.0.js:2979)
(anonymous function) (c3-0.3.0.js:2080)
(anonymous function) (d3-3.4.9.js:1052)

This is using 0.3.0

**Comment by masayuki0812** [comment]
This issue was fixed by this commit https://github.com/masayuki0812/c3/commit/01aa08ac4ac375c41e614e3e7d5b3f30c4f2f0d1 in the latest version `0.4.10`, so let me close at the moment. Thanks.
