### ISSUE TITLE
IE9 / IE10 / Phantomjs: MutationObserver support

### ISSUE THREAD

**Issue by raulgomis** [masayuki0812/c3#646]
I am having some troubles with PhantomJS and MutationObserver. Since PhantomJS is based on Safari 5.1, MutationObserver functionality is not supported by default. See for details: http://caniuse.com/#feat=mutationobserver 

Also IE9 / IE10 have not support for MutationObserver. I consider that IE9 / IE10 are not so old to deprecate support for them. jQuery 2.x (have support IE9+) and Angular 1.3 as well IE9+. It would be great to fallback to MutationEvents. 

It's a pain not to test c3 using PhantomJS so I consider it would be a great feature for c3.

**Comment by aendrew** [comment]
I'm closing this issue because it's an issue with PhantomJS and not C3, and a variety of solutions have been documented.
