### ISSUE TITLE
Firefox - Bar chart - Resizing, Visual Glitch

### ISSUE THREAD

**Issue by ggamir** [masayuki0812/c3#651]
In firefox, bar chart resizing causes visual glitches (some phantom lines) while the resizing is happening. I wasn't able to capture it in a snapshot because it appears and disappears quickly after the resizing is done, but it is reproducible.

**Steps to reproduce:**
1) Use Firefox to open this JS Fiddle http://jsfiddle.net/vsua2fud/4/
2) Resize (smaller, bigger, back and forth) the browser window horizontally, or even just the pane with the rendered chart so that the chart resizes.
3) Notice there are momentarily glitchy lines near the bars as they change size. The glitches appear and disappear quickly as the resizing occurs, and when its finished / stable, the chart looks normal again.

**Comment by masayuki0812** [comment]
This seems not happening in the fiddle using the latest version `0.4.10`, so please let me close at the moment. Thanks.
