### ISSUE TITLE
Layout/resize bug on rotated charts when categorical X axis has 2 or more long labels

### ISSUE THREAD

**Issue by dustinlarimer** [masayuki0812/c3#760]
Here's a fun one! :)

When resizing (and occasionally when first loading) a chart with the following attributes, the chart collapses into an unrecognizable mess (screenshot below):
* Rotated axis
* Categorical X axis
* Two or more long labels (multiline candidates)

```
axis: {
  x: {
    type: "categorical",
    categories: [ /* Two or more long labels */ ]
  },
  rotated: true
}
```

![screen shot 2014-11-24 at 2 28 08 pm](https://cloud.githubusercontent.com/assets/180438/5174619/b5aa29bc-73e7-11e4-8600-076116d9d590.png)

http://jsfiddle.net/ugh2dvsx/3/

**Comment by masayuki0812** [comment]
@dustinlarimer Is this still happening in the latest version `0.4.10`? Some issues about the padding for left side have been fixed, so this might be ok now as well.

**Comment by masayuki0812** [comment]
It seems not happening in the fiddle (using 0.4.10).
