### ISSUE TITLE
Charts intercept drag events and prevent scrolling on touch devices

### ISSUE THREAD

**Issue by aendrew** [masayuki0812/c3#798]
Likely related to #687, the charts intercept the `touchstart` event and thus prevent scrolling. If you have a chart that fills the entire viewport, this basically locks scroll to the chart and prevents the user from accessing the rest of the page. Turning interactions off fixes the issue.

Marking as bug.

**Comment by aendrew** [comment]
Marking as a duplicate of #215 and closing.

**Comment by masayuki0812** [comment]
:+1:

**Comment by masayuki0812** [comment]
I pushed the fix. Please see #215 .

**Comment by aendrew** [comment]
@masayuki0812 OMG amazing, you're the best. That means I can truly close times/axisJS#46 for good, and am one step closer to my 1.0.0 release! Thanks a tonne! :+1: :shipit:

**Comment by iamnathadian** [comment]
@aendrew It looks like you are the owner of the C3 package on NuGet. Would you be able to update it with the latest version of C3?

**Comment by aendrew** [comment]
@iamnathadian Noticed your other issue. Attempting to do so now, but I really don't use NuGet, @Syzen33 just sort of gave me admin access, but I'm a Mac user. 

#totallydoesnotgetwhypeopleuseNuGet

**Comment by iamnathadian** [comment]
Visual Studio integrates really well with NuGet, so that makes it a really easy way to pull third party libraries into our projects.
