### ISSUE TITLE
Update X axis values when loading the data dynamicly

### ISSUE THREAD

**Issue by ergo** [masayuki0812/c3#827]
Hello,

As per this example: http://jsfiddle.net/bt56r29q/46/ , (real app has way more ticks with hour resolution)
I'm creating a chart and updating it's values via ajax call in my angular app, I would like to set the X ticks to only full days on midnight,
I've tried few ways but I can't figure out how to set the x values when calling load() on my chart.

**Comment by meenie** [comment]
For anyone wondering, this worked for me.

**Comment by aditya-padhi-kbl** [comment]
Hi, this approach doesn't work.
I am using "c3": "^0.4.18" and
"@types/c3": "^0.4.44"

**Comment by meenie** [comment]
@aditya-padhi-kbl We are using `0.4.11`.

**Comment by Hari-KrishnanV** [comment]
The method "chart.internal.config.axis_x_tick_values = [1418634000000, 1418637600000, ...];" is not working. It says, chart doesn't have a property "internal".
"c3": "^0.4.23"
