### ISSUE TITLE
Area chart only fills values from zero

### ISSUE THREAD

**Issue by luketheobscure** [masayuki0812/c3#829]
I have an area chart with values ranging from -50 to +100. I would like the area to always fill from the bottom, but unfortunately it seems to only shade the area between the value and 0. Is there any way to override this?

![screen shot 2014-12-16 at 7 55 23 am](https://cloud.githubusercontent.com/assets/1163812/5456516/edaa2f3e-84f8-11e4-81b3-20d4bae81f2c.png)

**Comment by masayuki0812** [comment]
v0.4.9 has been released, so please let me close.

**Comment by heckmac** [comment]
hi @masayuki0812; have you released it at the end? 
It does not seem to work to me, but maybe I didn't get it how to use it.
