### ISSUE TITLE
new align option in grid.x.lines

### ISSUE THREAD

**Issue by TheHalcyonSavant** [masayuki0812/c3#834]
There isn't a setting for text alignment over the horizontal grid line, so I'm proposing a new option:
```js
grid: {
  y: {
    lines: [{
      label: {
        text: 'Some text',
        position: 'start' // can be start|middle|end(default)
      }
    }]
  }
}
```
The change from text to label is following the current `axis.labels` setting standard.

`position` can be `start`, `middle` or `end` (the same as the SVG text-anchor standard)
`position`: 'start' should modify the grid line SVG to this:
```html
<g class="c3-ygrid-line">
  <line y2="..." y1="..." x2="..." x1="..."></line>
  <text text-anchor="start" dy="-5" dx="5" style="opacity: 1;" y="...">
    Some text
  </text>
</g>
```
What do you think, can C3 be improved like this ?

**Comment by daseinhorn** [comment]
+1 for this.
Have you found a way to do it without the option being implemented?

**Comment by Akanoa** [comment]
+1
I'm agree with you.

**Comment by masayuki0812** [comment]
I implemented in this commit: https://github.com/masayuki0812/c3/commit/c485308f4561b1d252d28dc2e519f8a662fb5a09 , then I'll release this in the next version `v.0.4.10`.

**Comment by daseinhorn** [comment]
Will it be released with v.0.4.10-rc.2?

**Comment by masayuki0812** [comment]
@daseinhorn yeah, it was released.

**Comment by masayuki0812** [comment]
`0.4.10` has been released, so I'm closing this issue. Thanks.
