### ISSUE TITLE
Update c3 to support the last d3 version

### ISSUE THREAD

**Issue by raulgomis** [masayuki0812/c3#849]
Hi all, 
At the moment c3 supports d3 3.4.4 version. Anyone knows if the latest version is supported? and why c3 was locked to support this version? I would be great to support the last d3 version (v 3.5.2 at the moment).

**Comment by masayuki0812** [comment]
Sorry, there is no reason that I didn't update d3 version. So, As @aendrew wrote, it seems ok to update it , then I pushed a commit here https://github.com/masayuki0812/c3/commit/aa38b870baf4d432a23fa8c6d66a751ae0b67ea9

**Comment by masayuki0812** [comment]
I think now this issue can be closed, so please let me close. Thanks.

**Comment by aendrew** [comment]
Yay! Thanks! :+1: :shipit:
