### ISSUE TITLE
Additinal y axis is limited to 1

### ISSUE THREAD

**Issue by VishalAdPushup** [masayuki0812/c3#852]
I am trying to show multiple series on spline chart, The data in all series has great difference and thus if I use single y axis, series with smaller data sets drops down to x axis and series with larger data is shown properly.

I tried adding additional y axis, but found that it is limited to 1, Is there any way by which I can get what I want.

**Comment by masayuki0812** [comment]
Hi,  This is a duplicate of #112 , so please let me close. Thanks!

**Comment by VishalAdPushup** [comment]
Hi, Thank you for the feedback, I would love to contribute if you can help me with basic details to speed up.
