### ISSUE TITLE
on iPad when showing hidden series another series opacity is affected

### ISSUE THREAD

**Issue by agdev** [masayuki0812/c3#853]
Hi,

On iPad Air with latest iOS 
when showing hidden series another series opacity is affected, try this fiddle:
http://jsfiddle.net/agcsi/w6g5pths/1/
Steps:
1. hide data1
2. unhide data1
Check data2, it is barely seen.

C3js version: 0.4.8

**Comment by masayuki0812** [comment]
Hi,
Sorry I don't have that device, but this happens only on that device?

**Comment by agdev** [comment]
Hi,
I checked only on iPad, I think, fading of a series that occurs on mouse over in windows happens on click event on iPad. I think the best it is to disable/avoid fading on tablets and smartphones.
Is there way I can disable fading ?

**Comment by masayuki0812** [comment]
I see, so how about setting `transition.duration = 0`?

**Comment by agdev** [comment]
I tried to change transition.duration = 0 in this example http://c3js.org/samples/transition_duration.html
I do not see that it changed fading at all.
Is it correct setting or other?

**Comment by masayuki0812** [comment]
Sorry, I misunderstood.. It's intended and correct behavior to fade out other series when one of the legend clicked. If you want to change this behavior, please set `legend.item.onclick` like:
```
legend: {
  item: {
    onclick: function (id) {
      this.toggle(id);
      this.revert();
    }
  }
}
```
Can you try this? Thanks.

**Comment by agdev** [comment]
works, thanks
