### ISSUE TITLE
Data Labels Format Does Not Work For Separate Data Sets

### ISSUE THREAD

**Issue by KoltonG** [masayuki0812/c3#854]
**Description:** In the documentation it says that you can set the format of each data set

```javascript
data: {
  labels: {
    format: function (v, id, i, j) { ... }
    // it's possible to set for each data
    //format: {
    //    data1: function (v, id, i, j) { ... },
    //    ...
    //}
  }
}
```

However in the example and on my own I could not get this to work. All I was able to get working was all the __y__ element would share the same format for example having the $ prefix to the number.

**The example on the site shows how to make it work for all Y data, however not for single data sets as in a separate format for data1 and data2**

http://c3js.org/samples/data_label_format.html

**Comment by masayuki0812** [comment]
Hi,
You're right. It's been fixed now and I'll release in the next version v0.4.9. Thanks!

**Comment by masayuki0812** [comment]
v0.4.9 has been released, so please let me close.
