### ISSUE TITLE
Calling resize on each and every window resize drammatically slows down the browser

### ISSUE THREAD

**Issue by denisvmedia** [masayuki0812/c3#857]
If you have a lot of charts and use Firefox (this issue appears in other browsers as well, but it slows down especially Firefox), resizing the window can be a huge pain (resizing is fired not only when you resize the window itself, but also when you open Firebug, for example). This happens because `$$.api.flush();` is called on every resize event call. Which can be tens of times. Instead of calling it on each resize event call, I suggest using the following code:

```js
        if (window.onresize.add) {
            var timeout;
            window.onresize.add(function () {
                config.onresize.call($$);
            });
            if (config.auto_resize) {
                window.onresize.add(function () {
                    if (timeout !== undefined) {
                        clearTimeout(timeout);
                    }
                    timeout = setTimeout(function() {
                        $$.api.flush();
                    }, 100);
                });
            }
            window.onresize.add(function () {
                config.onresized.call($$);
            });
        }
```

`$$.api.flush()` will be called not more than once per 100ms (the number is random here, I didn't make a lot of tests, which one is the best).

Also, please note `auto_resize` setting. It could be used to turn off auto resizing the charts. By default it should be true for backwards code compatibility.

I hope, you got my idea and this can go to the core.

**Comment by aendrew** [comment]
@denisvmedia Looks good! Mind submitting this as a pull request and referencing this issue in the commit? Thanks!

**Comment by udhaya2kmrv** [comment]
I am also facing same problem.  I have an multiple charts in single page. When i scroll down in ipad window.resize function called. Any possible solution let us know?

**Comment by denisvmedia** [comment]
@udhaya2kmrv check my pull request in #860
You can apply it to the sources manually, until it gets merged to the official c3js release.

**Comment by udhaya2kmrv** [comment]
thanks its great, I work it manually but it does not work above pull request.i have twenty chart in single page. I scroll it down so ipad url bar hide that time trigger onresize event to call twenty chart for resizing it slow down scroll.
Is there any solution for that?

**Comment by denisvmedia** [comment]
@udhaya2kmrv you may want to disable onresize event handler at all by setting config.auto_resize to false (this setting comes with the PR as well).

**Comment by udhaya2kmrv** [comment]
Then if i disable permenantly then how i handle resize

**Comment by denisvmedia** [comment]
Resize in which case? Orientation change? Then bind to orientationchange and trigger `$$.api.flush()` manually.

**Comment by udhaya2kmrv** [comment]
Yes i did it. Its working fine now.. thank you @denisvmedia :)

**Comment by udhaya2kmrv** [comment]
How to bind $$.api.flush() for orientation change and chart element(written div) is increase?

**Comment by masayuki0812** [comment]
Sorry for the late response. Merged now. Thanks!
