### ISSUE TITLE
Is it possible to set by default zoom of chart ???

### ISSUE THREAD

**Issue by kumar31rajesh** [masayuki0812/c3#858]
I want to set by default some zoom to chart initially because for large data chart become cluttered.

**Comment by masayuki0812** [comment]
Can you try `axis.x.extent`? It's in the reference http://c3js.org/reference.html .

**Comment by masayuki0812** [comment]
And please ask this kind of question in GoogleGroup as mentioned here https://github.com/masayuki0812/c3#using-the-issue-queue
So, please let me close now. Thanks.
