### ISSUE TITLE
Can we have varchar in the x-axis other than numeric. eg: I need to give month name in the x-axis like Jan, Feb etc ... can we do? 

### ISSUE THREAD

**Issue by shilparani** [masayuki0812/c3#863]
Currently C3 is able to accept numeric values only ....

**Comment by aendrew** [comment]
@shilparani This is done with [categorical axes](http://c3js.org/samples/categorized.html).

For future reference, mind asking support requests in the [Google Group](https://groups.google.com/forum/#!forum/c3js) instead? We try to keep the issue queue reserved for bug reports and whathaveyou. Thanks!

Closing as resolved; if I still haven't answered your question, please let me know and I'll repopen. :smile:

**Comment by shilparani** [comment]
Thanks!
