### ISSUE TITLE
generate two charts side-by-side into the same DIV

### ISSUE THREAD

**Issue by DemarsM** [masayuki0812/c3#867]
In the doc bindto append the chart to the element but it seems it overwrite the chart if there was already one in the element.

How can I generate two charts side by side without binding them to two differents div?

**Comment by jmnunezizu** [comment]
@DemarsM why can't you just use 1 parent container and two child divs, one for each binding/chart? That's what I do.

**Comment by jmnunezizu** [comment]
@DemarsM I still believe that the relationship between a chart and a div is 1:1, and it's up to your code to create the containers as necessary.

**Comment by masayuki0812** [comment]
c3 does not support this functionality now. Additionally, it seems unusual use case, so I expect c3 won't support that in the future. Anyway, the doc should not use "append", so I've updated.

**Comment by masayuki0812** [comment]
Please let me close. Thanks.
