### ISSUE TITLE
How to simulate legend item click

### ISSUE THREAD

**Issue by byronanderson** [masayuki0812/c3#871]
We would like to have the ability to test the functionality of the legend item data series toggling.  Mouse clicks work, but jQuery clicks do not.

I was expecting this to work:

```javascript
$($('.c3-legend-item')[0]).click();
```

What am I doing wrong?

**Comment by masayuki0812** [comment]
MouseEvent seems to work as I used in spec: https://github.com/masayuki0812/c3/blob/master/spec/c3-helper.js#L13

**Comment by masayuki0812** [comment]
Please let me close because it's not a bug. Instead, you can ask in GoogleGroup https://groups.google.com/forum/#!forum/c3js Thanks.
