### ISSUE TITLE
Trimmed rotated x category labels

### ISSUE THREAD

**Issue by Timopheym** [masayuki0812/c3#872]
http://jsfiddle.net/snhptquj/1/

If labels too long it does not show them properly. Where to look for?

p.s. Multilines are cuted too, something with margin calculation.

**Comment by masayuki0812** [comment]
Thank you for reporting. It's a bug, so I fixed by the commit above. I'll release this fix in the next version v0.4.9. Thanks!

**Comment by Timopheym** [comment]
@masayuki0812 Thanks you very much! You are the best (i really tried a lot of charts =).

**Comment by Timopheym** [comment]
It seems to me, that current version is more slow, then previous version, could it be?

**Comment by masayuki0812** [comment]
Yes, I didn't release that fix yet. The next version v0.4.9 will include this fix and I'll release it shortly.

**Comment by masayuki0812** [comment]
v0.4.9 has been released, so please let me close.
