### ISSUE TITLE
generateColor gets wrong color during select/unselect path

### ISSUE THREAD

**Issue by solgarius** [masayuki0812/c3#874]
I have noticed when performing unselect on a path the 'd' node that is passed through to generate color is the object that contains a 'data' sub object with no id. This results in generateColor function not finding the color for the selected/unselected element and it will then just change the color of that path to the next unused color in the list of colors. 

This is probably best seen in a pie chart. See: http://jsfiddle.net/lakerz/n8hqk3z1/
Steps to replicate:
1> select a pie segment
2> select a second pie segment
Note that the first segment is now red instead of its original color.

The fix for this should be pretty simple. It should be something along the lines of:
```javascript
c3_chart_internal_fn.generateColor = function () {
        var $$ = this, config = $$.config, d3 = $$.d3,
            colors = config.data_colors,
            pattern = notEmpty(config.color_pattern) ? config.color_pattern : d3.scale.category10().range(),
            callback = config.data_color,
            ids = [];

        return function (d) {
            var color;
            var id = d.id || (d.data && d.data.id) || d;

            // if callback function is provided
            if (colors[id] instanceof Function) {
                color = colors[id](d);
            }
```

**Comment by aendrew** [comment]
Ah. That indeed looks like a bug. Wanting to submit a pull request...? :smile:

**Comment by masayuki0812** [comment]
Thank you for reporting. I think this has been fixed by the commit above and I'll release as v0.4.9 shortly. Thanks.

**Comment by masayuki0812** [comment]
v0.4.9 has been released, so please let me close.

**Comment by solgarius** [comment]
Thanks @masayuki0812, works perfectly.
