### ISSUE TITLE
Is there a way to remove the tick marks?

### ISSUE THREAD

**Issue by gwintrob** [masayuki0812/c3#876]
For example, I would like to keep the dates (e.g. "2013-01-02") but not the small vertical tick mark ("|") above each one.

![screenshot 2015-01-09 00 14 43](https://cloud.githubusercontent.com/assets/1240085/5677012/ae04ab08-9794-11e4-9da3-00d1da666158.png)

Setting `axis.x.tick.width` to 0 does not seem to fix this issue.

Thanks for your help.

**Comment by gordol** [comment]
https://github.com/masayuki0812/c3/commit/89ee5145d66c97f235f8443146669c491556846a

**Comment by gordol** [comment]
https://github.com/mbostock/d3/wiki/SVG-Axes

**Comment by gwintrob** [comment]
Sorry, I should've used the Google Group.  Thanks for the link @gordol.

**Comment by aendrew** [comment]
Also, just to close this:

CSS:
```
.c3-axis .tick line {display: none;}
```
