### ISSUE TITLE
space between y axis and begin of line in line chart

### ISSUE THREAD

**Issue by tchiloh** [masayuki0812/c3#878]
The space between y axis and begin of line in line chart is not pretty. 
![untitled](https://cloud.githubusercontent.com/assets/10463985/5680416/5a81b84e-980d-11e4-9f69-a90f9957110d.jpg)

Can I set the padding to 0?

**Comment by masayuki0812** [comment]
Can you try `axis.x.padding = 0`? And please ask this kind of question in GoogleGroup https://groups.google.com/forum/#!forum/c3js . Thanks.
