### ISSUE TITLE
"After rendering" or "on rendered" event

### ISSUE THREAD

**Issue by leandrotv** [masayuki0812/c3#880]
Is there a feature like this already or anything planned?

**Comment by masayuki0812** [comment]
Not yet, but please let me mark as enhancement.

**Comment by masayuki0812** [comment]
I just added `onrendered` callback and I'll release this new feature in the next version v0.4.9 shortly.

**Comment by masayuki0812** [comment]
v0.4.9 has been released, so please let me close.

**Comment by leandrotv** [comment]
Great! Thanks a lot!

**Comment by samhuntsocial** [comment]
when chart is initialized (e.g. chart.generate) , onrendered callback() works. 
when chart is redrawed (e.g. calling chart.generate again...as i can't get chart.load to work properly), onrendered callback() doesn't get called. 

seems like onrendered() behaves exactly like oninit()?

**Comment by masayuki0812** [comment]
I don't think so. Can you see this fiddle? http://jsfiddle.net/7kYJu/985/ And it would be helpful if you can give us a fiddle to reproduce. Thanks.

**Comment by keshav-goibibo** [comment]
@masayuki0812 I think what @samhuntsocial is saying is right. In the above provided jsfiddle which you have mentioned also shows the same behaviour. Before even the graph is rendered on screen it shows the alert "rendered". Please check your jsfiddle again.

**Comment by MihaiBratulescu** [comment]
This is not working for me. The series are not yet printed on the page until after ajax success finished but I need to upload the SVG back to the server right after the chart is generated.

Not even waiting a few seconds helps because d3 won't finish it's job.
