### ISSUE TITLE
Weird behavior with barchart

### ISSUE THREAD

**Issue by yanndebelgique** [masayuki0812/c3#884]
Im having issues with the barchart. When I swap data (i.e. unload the old, load the new) the bars of the new data does not render correctly. It shows the same height for all categories. But they are not the same! And when I hover over the bars it shows me different values. So it seems that only the bars are not showing correctly.

![image](https://cloud.githubusercontent.com/assets/2687189/5697444/d0d4da28-99f0-11e4-900f-c5606eb8036c.png)

btw great work! beautiful charts!

**Comment by yanndebelgique** [comment]
This is def not right :

![image](https://cloud.githubusercontent.com/assets/2687189/5701457/de16c2a4-9a4b-11e4-8fc0-de9b32f98dd5.png)

Im doing something wrong but I don't know what... I simply unload everything and put new data back in. Im using meteor.js

**Comment by masayuki0812** [comment]
Can you give us the code to reproduce? Your link seems invalid now.

**Comment by yanndebelgique** [comment]
sorry my mistake...
