### ISSUE TITLE
Cannot Set Y Axis Min Greater than Max for Inverted Axis since 4.0

### ISSUE THREAD

**Issue by alexphelps** [masayuki0812/c3#885]
When upgrading from 3.0 to 4.0 I am unable to set Y Axis Min Value to be greater than the Max value to have an inverted axis (ie 0 at the top and 50 at the bottom)

Working example with 3.0:
```js
y: {
    max: -10,
    min: 50,
      padding: {
                top: 10,
                bottom: 0
      }
}
```

This produces a graph like this

![2015-01-12_10-19-45](https://cloud.githubusercontent.com/assets/674282/5698657/0ac3ac74-9a45-11e4-9ddb-39ea373fbafb.jpg)

How could I get this to work again?

Or what are my options for having an inverted y axis?

**Comment by masayuki0812** [comment]
Hi, I fixed this issue and additionally I introduced `axis.y.inverted` option to inverted the direction of y axis as your use case. So, now you can do that by setting as you did like this example, or using this new option like `axis.y.inverted = true`.
Anyway, can you try these again? I'll release this in the next version v0.4.9 shortly.

**Comment by alexphelps** [comment]
@masayuki0812 - Perfect! It's working now. 

Here is my test code and screenshot below of the axis inversion. 

```js

y: {
              inverted: true,
              max: 50,
              min: 0,
              padding: {
                top: 5,
                bottom: 0
              }
            }

```


![screen shot 2015-01-18 at 11 22 53 am](https://cloud.githubusercontent.com/assets/674282/5791367/721adee2-9f04-11e4-9d3d-f8815d700286.png)

**Comment by masayuki0812** [comment]
Thank you :+1:

**Comment by masayuki0812** [comment]
v0.4.9 has been released, so please let me close.
