### ISSUE TITLE
Pie\Donut chart does not react to hidden labels

### ISSUE THREAD

**Issue by Timopheym** [masayuki0812/c3#886]
http://jsfiddle.net/rvvubo47/2/ - Here we can see, that if we set to not show label, it still stays there.

also my plugin to show\hide labels do not work with pie\donut layout

```js 
c3.chart.fn.data.labels = function (state) {
    var $$ = this.internal;
    $$.config.data_labels = state;
    $$.redrawWithoutRescale();
};
```

So Pie\Donut charts don't gets value from config.data_labels.

**Comment by aendrew** [comment]
Hi @Timopheym!

You need to use [`pie.label.show`](http://c3js.org/reference.html#pie-label-show), not `data.labels`. 

In the future, could you please ask such questions on the [Google Group](https://groups.google.com/forum/#!forum/c3js)? We're trying to keep the issue queue tidy for bug reports and whathaveyou. The Google Group is also better setup to deal with ongoing support requests.

Thanks!
