### ISSUE TITLE
Bar chart shows null values

### ISSUE THREAD

**Issue by Czachur** [masayuki0812/c3#887]
I have created a bar chart and if it is passed a null value, it still shows on the graph (as 0). Is there a way to hide null values, or another value to assign to guarantee it isn't shown on the graph?

Thanks

**Comment by aendrew** [comment]
Hi @Czachur! Try passing `null` instead of `0`. 

In the future, could you please ask such questions on the [Google Group](https://groups.google.com/forum/#!forum/c3js)? We're trying to keep the issue queue free for bug reports and software development purposes. Thanks!
