### ISSUE TITLE
Custom tooltip values

### ISSUE THREAD

**Issue by benjaminbaldoni** [masayuki0812/c3#891]
Hi, I'm displaying a percentage bar chart, but I would like that the tooltip show not the % value, but another value

e.g: for Step1 = 1000, Step2 = 800 the chart would be this one http://jsfiddle.net/3n149u72/1/

Is there any way to display the step value instead of the % in the tooltip (e.g: Step1 - Value: 1000)? I tried a few workarounds, like hiding another chart containing the values, but none of them worked like I intended...

Thanks in advance.

**Comment by aendrew** [comment]
Hi @benjaminbaldoni!

You can use [`tooltip.format`](http://c3js.org/samples/tooltip_format.html) for this.

Example: http://jsfiddle.net/aendrew/u77yt5pu/1/

In the future, could you please ask such questions on the [Google Group](https://groups.google.com/forum/#!forum/c3js)? We're trying to keep the issue queue reserved for bugs and feature requests. Thanks!

**Comment by benjaminbaldoni** [comment]
Oh, sorry about that, sure, next time I will.

Thanks for the answer!
