### ISSUE TITLE
box plot

### ISSUE THREAD

**Issue by daise** [masayuki0812/c3#892]
hi,
Box plot graph can be done in c3?

**Comment by aendrew** [comment]
Isn't that just like a candlestick chart? Marking as a duplicate of #121; if I'm wrong, please let me know and I'll reopen. Thanks!

**Comment by rutgerbogaerds** [comment]
A candlestick chart is not the same as a boxplot.
A boxplot has a extra bar in the box (median value) and optional outlayers (points above1,5 IQD distance from median).
