### ISSUE TITLE
Provide the supported version of d3 in c3 releases

### ISSUE THREAD

**Issue by wfortin** [masayuki0812/c3#893]
It should be documented that the supported version of d3 is currently `3.4.3`. I've investigated long to fix https://github.com/mbostock/d3/issues/2174 to find out that my issue was that I included a newer version of D3.

Please document the officialy supported d3 version or provide d3 in the c3 release.

Thanks a lot for the great reusable library !

**Comment by aendrew** [comment]
@wfortin That's very good to know. We recently updated our D3 dependency; a regressive, IE-specific issue like that would've gotten past all of our automated tests.

@masayuki0812, think we should rollback?

**Comment by masayuki0812** [comment]
Thank you for reporting. I confirmed c3 works with d3 up to version `3.5.0`, so updated the dependency to `<=3.5.0`.

**Comment by masayuki0812** [comment]
And I added dependency to README.

**Comment by masayuki0812** [comment]
v0.4.9 has been released, so please let me close.
