### ISSUE TITLE
Zoom question

### ISSUE THREAD

**Issue by psinghsp** [masayuki0812/c3#894]
There is an example on c3 which uses "mouse wheel" to zoom in. My question is: can I use drag selection to rubber-band a rectangle and use that to zoom in?

I see this behaviour in a sub-chart - but we do not have sub charts and would like to zoom in the main chart using selection rather than middle mouse wheel.

If this functionality does not exist, will it be easy to look at source and add this ability - I know some d3.js and am not entirely familiar with c3 internals.

**Comment by aendrew** [comment]
Hi @psinghsp! This would be a really good question to ask the [Google Group](https://groups.google.com/forum/#!forum/c3js). There might be a way to do it already, just I'm not familiar with it. Mind asking there? Thanks!
