### ISSUE TITLE
tooltip should not disappear on data flow

### ISSUE THREAD

**Issue by J-F-Liu** [masayuki0812/c3#898]
Tooltip should disappear only when mouse position is changed, otherwise the use don't have enough time to read the values if the flow speed is once per second.
If the data point on mouse position is chagned after flow then contents on tooltip can automatically update.

**Comment by aendrew** [comment]
Confirming, just tried to read tooltips on the [flow example](http://c3js.org/samples/api_flow.html) and @J-F-Liu is right, they're impossible to read. Marking as bug.

**Comment by masayuki0812** [comment]
This is intended, but it seems good to implement. So, please let me mark as enhancement.

**Comment by J-F-Liu** [comment]
Find a solution now:
remove the line `$$.tooltip.style("display", "none");` in `c3_chart_internal_fn.redraw` function
remove the line `$$.hideTooltip();` in `c3_chart_internal_fn.generateFlow` function

**Comment by aendrew** [comment]
@J-F-Liu Seems that would work — mind doing a PR? Thanks!

**Comment by J-F-Liu** [comment]
RP created.

**Comment by masayuki0812** [comment]
Merged your PR. I'll release this fix in the next version `0.4.11`. Thanks!!

**Comment by aendrew** [comment]
This has been merged into master so I'm closing. Thanks to @J-F-Liu for the PR!
