### ISSUE TITLE
c3 not defined

### ISSUE THREAD

**Issue by deepakumarln** [masayuki0812/c3#901]
i am getting c3 not defined after including all the js files and the css files.
pls reply asap.....................................................

**Comment by aendrew** [comment]
Could be any number of reasons, could you please do two things?

1. Create a Plunker or jsFiddle demonstrating what you're trying to do.
2. Post it to the [Google Group](https://groups.google.com/forum/#!forum/c3js), which is where we handle support requests (we generally keep the issue queue for bugs or feature requests).

Thanks!

**Comment by deepakumarln** [comment]
I solved the issue..........
thank you aendrew
