### ISSUE TITLE
font color not set for tooltips in c3.css

### ISSUE THREAD

**Issue by philhassey** [masayuki0812/c3#902]
On my website I've set td's to have a color of #fff, so tooltip text was invisible (white on white).  Here's a patch that fixes it.

.c3-tooltip td {
  font-size:13px;
  padding: 3px 6px;
  background-color:#fff;
  border-left:1px dotted #999;
  color: #000;
}

**Comment by masayuki0812** [comment]
Thanks. I added the style. I'll release this in the next version v0.4.9.

**Comment by masayuki0812** [comment]
v0.4.9 has been released, so please let me close.
