### ISSUE TITLE
Custom X-Grid lines don't handle chart padding correctly

### ISSUE THREAD

**Issue by davidpoore** [masayuki0812/c3#903]
When you have a chart with any amount of top padding, custom x grid lines render with too much top padding - it appears as though the padding is being applied twice. Here's a jsfiddle demonstrating the problem:   http://jsfiddle.net/Laephbw3/

I believe the x grid line should render all the way to the top of the chart, but the line ends before that.

**Comment by masayuki0812** [comment]
Thank you for reporting. I fixed this by the commit above. I think now it's ok and I'll release this in the next version v0.4.9 shortly.

**Comment by masayuki0812** [comment]
v0.4.9 has been released, so please let me close.
