### ISSUE TITLE
Question: Real time data - path transition

### ISSUE THREAD

**Issue by emilmork** [masayuki0812/c3#906]
I am interesting in creating a graph with real time data where i need to transform the x axis.

Like this example with d3: http://bost.ocks.org/mike/path/

Is this possible with c3 ? Or is it possible to use d3 within c3 to do the transition ?

**Comment by masayuki0812** [comment]
There is `flow` api in c3. Can you check this? http://c3js.org/samples/api_flow.html
Btw, please ask this kind of question in GoogleGroup https://groups.google.com/forum/#!forum/c3js first. Thanks!

**Comment by masayuki0812** [comment]
Please let me close at this moment.
