### ISSUE TITLE
bug decreasing line in line chart

### ISSUE THREAD

**Issue by tchiloh** [masayuki0812/c3#908]
In the line chart the line is not well drawn when there is  high amount of decreasing. 

example:
![image](https://cloud.githubusercontent.com/assets/10463985/5794451/b7579572-9f6d-11e4-8580-e5821c262e27.png)

**Comment by masayuki0812** [comment]
Can you give us a fiddle?

**Comment by tchiloh** [comment]
This problem is caused by this issue: https://github.com/masayuki0812/c3/issues/955

**Comment by aendrew** [comment]
@tchiloh Are you still experiencing this? The issue you referenced is closed, so closing this one in response. If you're still having issues, please let me know and I'll reopen. Thanks!
