### ISSUE TITLE
barchart x axis tick labels can collide even if there is the ability to add a line break

### ISSUE THREAD

**Issue by Gi7mo** [masayuki0812/c3#911]
see http://jsfiddle.net/4mLbok06/

**Comment by thegyorf** [comment]
Overlapping of the x-axis label can occur in a TimeSeries chart as well if there is a big jump in the time range of the ticks: http://jsfiddle.net/bpdy193t/

Though it may be a different issue than the BarChart one

**Comment by masayuki0812** [comment]
As @thegyorf said, bar type is not the cause, but it's an axis tick issue.
Can you try `axis.x.tick.width`? This option changes the width of axis x tick text, then the texts will be multiline. Or please use `axis.x.tick.rotate`. By this option, tick text will be rotated, so we can see the texts without overwrap.

**Comment by masayuki0812** [comment]
It's not a bug, so please let me close.
