### ISSUE TITLE
Multiple charts side by side

### ISSUE THREAD

**Issue by sunnypatel165** [masayuki0812/c3#912]
So, i have a view which demands 2 charts or 2 donutCharts side by side.
I cant do it because both divs will have to have id="chart".

How do i achieve this?
I tried running a script like:
```
 var donutChart1 = c3.generate({
        bindto: '.donutChart',
        data: {
            columns: [
                ['data3', 30],
                ['data4', 120],
            ],
            type: 'donut',
            onclick: function(d, i) {
                console.log("onclick", d, i);
            },
            onmouseover: function(d, i) {
                console.log("onmouseover", d, i);
            },
            onmouseout: function(d, i) {
                console.log("onmouseout", d, i);
            }
        },
        donut: {
            title: "Iris Petal Width"
        }
    });
```

with html as,

```
            <div class="col-md-6">
            <div id="donutChart"></div>
             </div>
```

Also tried replacing donutChart with donutChart1 in HTML. None works.

Please help me get 2 charts on a same HTML page.

**Comment by aendrew** [comment]
Hi @sunnypatel165 — this is more of a support question than a bug report, could you please ask on the [Google Group](https://groups.google.com/forum/#!forum/c3js)? Thanks!

(Though, try removing the "." in ".donutChart" in `bindto`)...
