### ISSUE TITLE
c3 chart color pattern change dynamically

### ISSUE THREAD

**Issue by udhaya2kmrv** [masayuki0812/c3#913]
Is it possible transform chart with new color pattern?

**Comment by Gi7mo** [comment]
sure see http://c3js.org/samples/api_data_color.html

**Comment by masayuki0812** [comment]
Thanks. It seems solved, so please let me close at this moment.

**Comment by sirberus** [comment]
This is not a solved issue. The issue is that color.pattern cannot be manipulated in the API, only data.color can be manipulated. See #1349
