### ISSUE TITLE
Continuous Line Tooltips

### ISSUE THREAD

**Issue by kdkavanagh** [masayuki0812/c3#917]
On a line chart, c3 can generate an interpreted spline. Is it possible to show tooltips when hovering anywhere on this line (displaying the interpolated value), rather than just when a single (non-interpolated) datapoint is hovered?  Perhaps something using d3.invert(mouse) and path.node().getPointAtLength()?

**Comment by masayuki0812** [comment]
Sorry, it's not possible and I don't think there would be much use case about this. So, please let me close at this moment and ask in GoogleGroup first. Thanks.
https://groups.google.com/forum/#!forum/c3js

**Comment by binakot** [comment]
Really needed feature!
