### ISSUE TITLE
Chart does not render properly when it was generated in not active tab in chrome

### ISSUE THREAD

**Issue by norecces** [masayuki0812/c3#924]
I opened http://c3js.org/samples/chart_combination.html from http://c3js.org/examples.html by clicking at link and opening it in new tab. Then I waited few seconds and went to combination example. It was not rendered (Actually it was but wrong). ![10](https://cloud.githubusercontent.com/assets/6973115/5832088/81a02ea0-a150-11e4-8c72-b94919b1db9c.png) 
To get chart visible I had to resize window. If it is only one tab in chrome, this bug does not seem to appear.

Google Chrome 39.0.2171.99 m

**Comment by tw3** [comment]
I saw the same bug in Chrome when rendering bar charts.  I was able to fix this by changing this line in c3.js:

$$.redrawBar(drawBar, false), // changed from true to false to fix bug (line 626)

**Comment by norecces** [comment]
Hi,

As I understand with this change in code you will loose smooth transitions.

Compare transition behaviour in http://c3js.org/samples/chart_bar_stacked.html and http://jsfiddle.net/norecces/sq5Lq7br/1/

**Comment by aendrew** [comment]
Marking this as a bug. #774 might allow @tw3's fix to be added to core while still enabling transitions.

**Comment by aendrew** [comment]
I've noticed this quite a lot recently working with C3, seems like if a chart is rendered and not painted, it will paint only upon being told to resize or flush or whatever. According to #936, charts also fail to render properly if they're not visible and are then made as such.

**Comment by aendrew** [comment]
See [this SO answer](http://stackoverflow.com/a/13748965/467760). It's a broader problem with D3, due to `requestAnimationFrame`.

IMO, the answer is 100% to drop all D3 `transition()` calls altogether in favour of CSS transitions/animations. See #774.

**Comment by maxio110** [comment]
Looks like this is not solved at all?

**Comment by fernandoluizao** [comment]
Seems like its already reported:

https://github.com/c3js/c3/issues/2458
