### ISSUE TITLE
Positioning of xaxis tick text

### ISSUE THREAD

**Issue by addywaddy** [masayuki0812/c3#927]
**What a fantastic library!!**

Is there any way to position the tick text? The default position is to start the text from the center of the column, and I was wondering whether it was possible to move the start point to the left to keep the text within the column.

![screen shot 2015-01-21 at 12 32 41](https://cloud.githubusercontent.com/assets/4456/5835488/9f044062-a169-11e4-942d-86d08d4f34c6.png)

**Comment by masayuki0812** [comment]
I think you can change the position by overriding `xForRotatedTickText` and `yForRotatedTickText` like `c3.chart.internal.xForRotatedTickText = function () { ... }`.

Btw, please ask this kind of question in Google Groups https://groups.google.com/forum/#!forum/c3js as noted here: https://github.com/masayuki0812/c3#using-the-issue-queue Thanks!

**Comment by addywaddy** [comment]
> Btw, please ask this kind of question in Google Groups https://groups.google.com/forum/#!forum/c3js as noted here: https://github.com/masayuki0812/c3#using-the-issue-queue Thanks!

Ah - will do. Thx!

**Comment by kavacky** [comment]
> I think you can change the position by overriding xForRotatedTickText and yForRotatedTickText like c3.chart.internal.xForRotatedTickText = function () { ... }.

Is this method renamed and/or moved?
