### ISSUE TITLE
How to make that, if the data changes. Selected on subshart not changed?

### ISSUE THREAD

**Issue by egor-a-trubnikov-panov** [masayuki0812/c3#928]
How to make that, if the data changes. Selected on subshart not changed?

**Comment by masayuki0812** [comment]
Hi, can you ask in GoogleGroup https://groups.google.com/forum/#!forum/c3js first as noted here https://github.com/masayuki0812/c3#using-the-issue-queue ? And I think it would be very helpful to describe the detail more :)
Then, please let me close at this moment. Thanks.
