### ISSUE TITLE
Label doesn't move on window resize

### ISSUE THREAD

**Issue by hodwik** [masayuki0812/c3#930]
Using Google Chrome Version 39, Firefox and IE, labels do not move when re-sizing the window.

From the example on c3js website:
![labels](https://cloud.githubusercontent.com/assets/5962056/5840029/955784ce-a160-11e4-9393-15fc0b1ad9b0.jpg)

**Comment by hodwik** [comment]
I tried wrapping the c3.generate({bindto: '#chart', ... }) function in a jquery $(window).resize();, so that the graphs will be re-rendered on window resizing, but this results in a memory leak that makes the page stop loading after a couple of resizings.

**Comment by bjlbernal** [comment]
I've also noticed this. Happens also on the c3js.org demo.

**Comment by masayuki0812** [comment]
Sorry, this is a bug happening from 0.4.9. And I pushed the fixed in #922 and will release in the next version 0.4.10 shortly. Thanks.

**Comment by masayuki0812** [comment]
`0.4.10` has been released, so please let me close. Thanks.

**Comment by bjlbernal** [comment]
As a third-party commenter on this issue, I will confirm that I am not seeing the issue with this release.

**Comment by aendrew** [comment]
@bjlbernal Thanks for confirming! :+1:
