### ISSUE TITLE
C3.js showing Error in IE 11 

### ISSUE THREAD

**Issue by kumar31rajesh** [masayuki0812/c3#931]
Hi ,
C3.js giving error at line 2531 Unspecified Error. can you tell me the reason for error and how to resolve it.

![image](https://cloud.githubusercontent.com/assets/5661805/5851831/d22f46c0-a232-11e4-85c5-86af9c69c3b6.png)

**Comment by aendrew** [comment]
Could you please provide a Plunker/jsFiddle and the exact versions of C3, D3 and IE11 you're running? I just tried to duplicate it using [this Plunker](http://plnkr.co/edit/o0M7FdPgo80vr6b2agq7?p=preview) on IE11.0.9600.17501, Windows 7 SP1 without success.

Closing for now as unable to replicate; will reopen if more information is given.
