### ISSUE TITLE
grunt running into jasmine errors regarding tooltip

### ISSUE THREAD

**Issue by bjlbernal** [masayuki0812/c3#932]
I am trying to upstream our code to v0.4.9. After merging our code changes and the new version into a transitional branch I ran grunt and was stopped by jasmine issues regarding tooltip. I then ran grunt against the clean upstream master and ran into the same issues.

When running grunt on the recent v0.4.9 code it produced the following errors.

```
 c3 chart tooltip
   tooltip position
     x encountered a declaration exception
       TypeError: 'undefined' is not a function (evaluating 'beforeAll(function () {
            tooltipConfiguration = {};
        })') in file:///C:/xampp/htdocs/dwportal/app/webroot/js/c3/spec/tooltip-spec.js (line 31) (1)
   tooltip positionFunction
     x encountered a declaration exception
       TypeError: 'undefined' is not a function (evaluating 'beforeAll') in file:///C:/xampp/htdocs/dwportal/app/webroot/js/c3/spec/tooltip-spec.js (line 92) (1)
```

Replacing 'beforeAll' with 'beforeEach' and commenting out the declaration at the top gets past that issue but then produces these errors.

```
 c3 chart tooltip
   tooltip position
     without left margin
       √ should show tooltip on proper position
     with left margin
       √ should set left margin
       √ should show tooltip on proper position
   tooltip positionFunction
     x should be set to the coordinate where the function returned
       Expected 115 to be 37. (1)
       Expected 289 to be 79. (2)
```

Removing the beforeAll wrappers( that I change to beforeEach previously) and letting the tooltipConfiguration json to be declared inline produces these issues.

```
 c3 chart tooltip
   tooltip position
     without left margin
       x should show tooltip on proper position
         Expected 37 to be 115. (1)
         Expected 79 to be greater than 280. (2)
     with left margin
       √ should set left margin
       x should show tooltip on proper position
         Expected 37 to be 115. (1)
         Expected 79 to be greater than 280. (2)
   tooltip positionFunction
     √ should be set to the coordinate where the function returned
```

I am a complete n00b regarding jasmine so my debug hacking above may be completely useless. Since I couldn't find anyone else mentioning the same thing I should first assume it has to do with my own set up. I am working on the code from a Windows 7 Lenovo (employer computer) and executing grunt from a msysGit terminal (my version dated the same as v1.8.5.2.msysgit.0, https://msysgit.github.io/).

Any ideas what it could be or questions requiring answers before you can help?

Thanks in advance.

**Comment by masayuki0812** [comment]
I think the version of jasmine is old and it's related to `grunt-contrib-jasmine` in package.json. So, can you try `npm update`?

**Comment by bjlbernal** [comment]
Thanks, ```npm update``` is throwing me errors resulting from dependencies for "node-gyp". Once I get that cleaned up I will let you know.

**Comment by bjlbernal** [comment]
After hours of installing all the prereqs around ```node-gyp`` and still running into issues. I took the suggestion from erikreppen commented on Nov 16, 2014 (https://github.com/TooTallNate/node-gyp/issues/518) to just go to nodejs.org and reinstalled. Success. Grunt works fine now. Closing.

Thank you.
