### ISSUE TITLE
Increasing size of donut label misaligns text

### ISSUE THREAD

**Issue by mschipperheyn** [masayuki0812/c3#933]
If I increase the size of the text inside the donut, the text no longer aligns vertically to the middle

    .c3-chart-arcs-title{
		font-size:34px;
		font-weight:bold;
		
	}

**Comment by masayuki0812** [comment]
Can you update `c3.css`. Now `.c3-chart-arcs-title` has `dominant-baseline: middle;` and it seems aligned nicely.

**Comment by mschipperheyn** [comment]
I found that I had included the stylesheet wrongly. With the stylesheet all works as expected

**Comment by masayuki0812** [comment]
OK. So, please let me close. Thanks.
