### ISSUE TITLE
tick.count returns "undefined" if axis is categorical

### ISSUE THREAD

**Issue by aendrew** [masayuki0812/c3#935]
Right now I think C3 tries to distribute the specified number of ticks across whichever axis `tick.count` is specified for. However, this isn't really joined up with the axis data, so it returns undefined. `tick.values` doesn't do anything with categorical axes AFAICT.

Plunker: http://plnkr.co/edit/ziuUfIYLdgnWmitXUbfg
![screen shot 2015-01-23 at 18 25 23](https://cloud.githubusercontent.com/assets/185041/5880083/3bc872dc-a32d-11e4-9519-ee48cf5aaf76.png)

**Comment by aendrew** [comment]
Worth noting that it just displayed the tick without a value in `0.3.0`; printing "undefined" seems like a regression from that.

**Comment by masayuki0812** [comment]
I fixed this to show empty string instead of `undefined`. I'll release in the next version 0.4.10 shortly. Thanks.

**Comment by aendrew** [comment]
Yay! Thanks! :+1:

**Comment by masayuki0812** [comment]
`0.4.10` has been released, so let me close. Thanks!
