### ISSUE TITLE
Regions (x axis) are not resized at all when zooming chart in 0.4.9

### ISSUE THREAD

**Issue by jruuska** [masayuki0812/c3#937]
Here's a fiddle using 0.4.9 http://jsfiddle.net/p5jow3o6/1/ 
compared to 0.4.8 http://jsfiddle.net/9am2fLdu/

Probably the same bug that is causing  https://github.com/masayuki0812/c3/issues/922

**Comment by aendrew** [comment]
Confirming.

**Comment by masayuki0812** [comment]
Yes, I fixed in #922 and will release in the next version. Thanks.

**Comment by masayuki0812** [comment]
`0.4.10` has been fixed, so let me close at the moment. Thanks.
