### ISSUE TITLE
changing tooltip

### ISSUE THREAD

**Issue by rotman** [masayuki0812/c3#940]
@tomcohen @masayuki0812 
Hello,

I'm using c3 library for my data visualization.
I want to change the tooltip that onmouseover the main graph, a smaller one will be generated below.
Is it possible?

thanks :)

**Comment by aendrew** [comment]
Hi @rotman!
This is a better question for the [Google Group](https://groups.google.com/forum/#!forum/c3js) — mind asking there?

Thanks!
