### ISSUE TITLE
Label text above bar graph

### ISSUE THREAD

**Issue by nsang92** [masayuki0812/c3#941]
Is it possible to add label text (such as totals above a stacked bar chart) above a bar in a bar chart? I have found a temporary fix, but it does not work well with re-sizing:

d3.selectAll('.c3-axis-x g.tick').each(function() {
                            var selectedtext = d3.select(this).text();
                                var translatestring = this.attributes[1].value;
                                var translatevalue = translatestring.substring(translatestring.lastIndexOf("(") + 1, translatestring.lastIndexOf(","));
                                chart.internal.main.append('text')
                                    .attr('y', 5)
                                    .attr('x', translatevalue)
                                    .attr('text-anchor', 'middle')
                                    .style('fill', 'black')
                                    .text('Summation Text');
                        });

**Comment by aendrew** [comment]
Hi @nsang92!

You're on the right path, you just need to create a function to reposition your elements that gets called on the `window.onresize` event. 

Might also want to consider using SVG `tspan` elements as well, which can help with text positioning. 

That said, this is neither a feature request or a bug, so could you please continue this discussion in the [Google Group](https://groups.google.com/forum/#!forum/c3js)? Thanks!
