### ISSUE TITLE
xFormat not parsing date correctly

### ISSUE THREAD

**Issue by pensierinmusica** [masayuki0812/c3#943]
Hi,

With this data and configuartion it looks like C3 is not parsing the dates correctly:

```javascript
var chart = c3.generate({
  height: 300,
  bindto: '#c3-chart',
  data: {
    x: 'date',
    xFormat: '%Y%m%d',
    rows: [
      ['date', 'price'],
      ['20140915', 50],
      ['20140916', 20],
      ['20140917', 10],
      ['20140918', 40],
      ['20140919', 15],
      ['20140920', 25]
    ]
  },
  axis: {
    x: {
      type: 'timeseries',
      tick: {
        format: '%Y-%m-%d'
      }
    }
  }
});
```

I made a quick [JS fiddle](http://jsfiddle.net/tmdvfay8/) to show what I mean.

Can you please check if I'm doing something wrong, or if it's a bug?

Thanks!

**Comment by n0thingness** [comment]
I'm encountering a similar error

	var chart = c3.generate({
		bindto: chart_div,
		data: {
			xs: {
				'PM2.5': 'PM2.5-x',
			},
			xFormat: '%Y-%m-%d',
			columns: [
				['PM2.5', 5, 10, 3, 15, 19, 7, 9],
				['PM2.5-x', "2014-12-24", "2014-12-25", "2014-12-26", "2014-12-27", "2014-12-28", "2014-12-29", "2014-12-30"],
			],
			type: 'spline',
		},
		x: {
			type: 'timeseries',
			tick: {
				format: '%Y-%m-%d'
			}
		}
	});

"NaN" shows up on the x-axis. No datapoints show up.

Some insight would be greatly appreciated.

**Comment by bendrexl** [comment]
It seems to be broken in the c3.js "Timeseries" example as well (by uncommenting the xFormat and corresponding 'x' row in the data) - all dates show 1969-12-31

**Comment by masayuki0812** [comment]
Thank you for reporting. This a bug and c3 was not able to handle string data correctly. A string that can be converted to number (e.g. `20150101`) was treated as unixtime, so I modified to always parse string date by using `xFormat` and treat x as unixtime only when it's a number.
I think now it's ok and I'll release this fix in the next version 0.4.10. Thanks.

**Comment by masayuki0812** [comment]
`0.4.10` has been released, so let me close at the moment. Thanks.

**Comment by jeremyshawnjackson** [comment]
Has this bug been resolved? I'm experiencing the same error with the code here http://jsfiddle.net/ertdnh2m/2/

**Comment by masayuki0812** [comment]
Thank you for reporting, but I found this happens because date values are given as number, not string. Can you see this fiddle (http://jsfiddle.net/ertdnh2m/4/) which I updated to give date values as string.

Btw, I don't think date values as number should not be handled as date format string nicely because date values as number (e.g. 1431267484058) can be given already. So, I'd like to keep current behaviour at the moment.

**Comment by samskrithib** [comment]
C3js not converting Unix time stamp properly.

http://jsfiddle.net/j9xs7ram/

See the second value "1486456770000" on-hover it shows ":30" 

@masayuki0812  Can you please help me how to solve this?

Many Thanks in advance.
