### ISSUE TITLE
Bar chart with x-axis min and max acts weird with one datapoint

### ISSUE THREAD

**Issue by RanzQ** [masayuki0812/c3#945]
I'd like to use the bar chart with a fixed x-axis min, max and values. But the padding and bar width calculation don't work nicely when min and max is set. Try modifying the example http://c3js.org/samples/chart_bar.html like this:
```
var chart = c3.generate({
    data: {
        columns: [
            ['data1', 30],
            ['data2', 30]
        ],
        type: 'bar'
    },
    axis: {
        x: {
            min: 0,
            max: 5,
            tick: {
                values: [0, 1, 2, 3, 4, 5]
            }
        }
    }
});
```
Would it be possible to base the calculations on min-max range and tick-count rather than point count in this case?

**Comment by aendrew** [comment]
Hi @RanzQ!

The reason this is happening is that the `x` axis in this case is index-based. By specifying `max: 5`, you tell C3 to ensure there's space for five data points. If there's only one (as there is in this case), it'll compress it into one side.

There totally is a bit of weirdness with `min` and `max` in the example you've given, though — `data1` is half as wide as `data2`, which doesn't make much sense, even if you're using it oddly (That is, you probably shouldn't specify min/max with indexed axes, C3 will take care of that generally. Min/max are really only used with numerical axes.).

Attaching screencap. @masayuki0812, not sure if I should tag this as `bug` or `invalid`?
![screen shot 2015-01-27 at 17 08 22](https://cloud.githubusercontent.com/assets/185041/5922927/56ffc1be-a647-11e4-9bb9-a40adbac42b3.png)

Also, can confirm it occurs in 0.4.9, not sure what version the website is currently running.

**Comment by RanzQ** [comment]
I made a temp fix by modifying `getMaxDataCount` to prefer `axis_x_tick_values` length if specified and greater than `maxDataCount` otherwise:

```
c3.chart.internal.fn.getMaxDataCount = function () {
    var $$ = this, config = $$.config,
        maxDataCount = $$.d3.max($$.data.targets, function (t) { return t.values.length; }),
        tickValues = config.axis_x_tick_values
    return tickValues && tickValues.length > maxDataCount ? tickValues.length : maxDataCount
};
```

That fixed the width problem I was having. For the min-max bug I just adjusted the min and max in case of one datapoint and it gets centered.

**Comment by masayuki0812** [comment]
Thank you for looking into this. Yeah, it's not intended, but it's a bug and width of bar should be computed correctly in this situation. So, I fixed by introducing `tickInterval`, which returns the length between ticks, and compute the width using this function.
I'll release this in the next version 0.4.10 shortly. Thanks.

**Comment by masayuki0812** [comment]
`0.4.10` has been released, so let me close at the moment. Thanks.
