### ISSUE TITLE
slow code on mouseover 

### ISSUE THREAD

**Issue by pehrlich** [masayuki0812/c3#948]
For a dataset of ~500 frames, I'm triggering a mousover every on every `window.requestAnimationFrame`, or 60 times a second.  I've found that commenting out the following code causes FPS to climb to 50+ from 30. Without any obvious difference. Perhaps some of this could be put behind a feature flipper, or the sort put in to a getter/setter rather than a mouseover?

https://github.com/masayuki0812/c3/blob/master/c3.js#L2303-L2322

```javascript
                selectedData = $$.data.targets.map(function (t) {
                    return $$.addName($$.getValueOnIndex(t.values, index));
                });

                // Sort selectedData as names order
                newData = [];
                Object.keys(config.data_names).forEach(function (id) {
                    for (var j = 0; j < selectedData.length; j++) {
                        if (selectedData[j] && selectedData[j].id === id) {
                            newData.push(selectedData[j]);
                            selectedData.shift(j);
                            break;
                        }
                    }
                });
                selectedData = newData.concat(selectedData); // Add remained

                // Expand shapes for selection
                if (config.point_focus_expand_enabled) { $$.expandCircles(index, null, true); }
                $$.expandBars(index, null, true);
```

**Comment by masayuki0812** [comment]
Hi, Thank you for pointing this out. As you said, this part is not used now. I think I forgot to remove when I   refactored or fixed something, so I just removed. Thanks!

**Comment by pehrlich** [comment]
:+1:

**Comment by masayuki0812** [comment]
`0.4.10` has been released, so let me close. Thanks!
