### ISSUE TITLE
Use API to change color function?

### ISSUE THREAD

**Issue by logworthy** [masayuki0812/c3#949]
I know you can use the API to change the mapping of colors to series (e.g. http://c3js.org/samples/api_data_color.html).

Is it possible to use the API to change the color _function_, like in the example below except _after_ the chart has been generated?

http://c3js.org/samples/data_color.html

**Comment by masayuki0812** [comment]
I think you can do that like this:
```
// var chart = c3.generate({ ... });
chart.internal.config.data_color = function (color, d) { return '#000000'; };
chart.internal.color = chart.internal.generateColor();
chart.flush();
```
This can be an API, but I'm not sure there is so much use case for that, so I didn't do that.

And can you ask this kind of question in Google Group first? Then, you could get an answer more quickly. Thanks. https://groups.google.com/forum/#!forum/c3js

**Comment by masayuki0812** [comment]
Please let me close at the moment and please reopen if it should be implemented as a new feature.
