### ISSUE TITLE
C3 don't work on my computer

### ISSUE THREAD

**Issue by kissinger99** [masayuki0812/c3#951]
Hallo!

I have installed the C3-files from here, then I change to the folder "httdocs" and wont start the examples.
But the site is blank, there is nothing to see.
What is wrong here?

Thank you!

**Comment by Tropicalista** [comment]
What error do you see in the browser console?

**Comment by aendrew** [comment]
Could you please direct support queries to the [Google Group](https://groups.google.com/forum/#!forum/c3js)? We try to keep the issue queue free for bug reports and feature requests.

Thanks!
