### ISSUE TITLE
Pie Chart Display Issues When Initial Data is Null

### ISSUE THREAD

**Issue by SamMorrowDrums** [masayuki0812/c3#952]
Hi, just thought it was worth a mention, if you work in asynchronous land, and you have to put graphs on the page before the data, I normally put single null values for each data section I'm expecting.

This stops the pi chart from rendering correctly (better to put the names, but no values).

Setting values to `null` causes all subsequent updates to only render one segment, until you mouseover it.

![screen shot 2015-01-28 at 15 25 02 copy](https://cloud.githubusercontent.com/assets/4811358/5940616/f4c9d72e-a703-11e4-8c54-39bc891ef7ec.jpg)

**Comment by masayuki0812** [comment]
Thanks for reporting. You're right, and I think it's been fixed now. I'll release this fix in the next version v0.4.10. Thanks.

**Comment by masayuki0812** [comment]
`0.4.10` has been released, so let me close at the moment.
