### ISSUE TITLE
Complex whale curve chart

### ISSUE THREAD

**Issue by daseinhorn** [masayuki0812/c3#953]
I try to create a rather complex chart as seen in this picture:
![soll](https://cloud.githubusercontent.com/assets/1166696/5942423/cbf0ca56-a717-11e4-9eb6-209cb08cf8af.png)

I do have the basic curve that is working just fine. I also have the grid working as expected. But here is my first question: As you can see in the picture, the y axis has to be "replaced" and should only show the two values from the y-grid. How would you accomplish that?

The same thing has to be done with the x axis as you can see. I do have the value (100/14/20) calculated so I just have to replace the values on the x axis with the values I have calculated. Is there a way to do that? 

Thanks, 
daseinhorn

**Comment by SamMorrowDrums** [comment]
Look at the C3 Axis options, for example:

```Javascript
axis: {
    y: {
        format: function (val) {
            return val * 256;
        },
        fit: false,
        count: 6
    }
}
```

**Comment by masayuki0812** [comment]
Can you try `axis.x.tick.values` and `axis.y.tick.values`? We can set tick values manually by this options.
http://c3js.org/reference.html#axis-x-tick-values
http://c3js.org/reference.html#axis-y-tick-values

**Comment by SamMorrowDrums** [comment]
You can also label the axis grid lines with values, that way you don't have to remove the axis numbers?

For example, I use a pump efficiency curve to show and add in a Y Line, and an X Line to show the current efficiency, and the flow rate, with the values on the lines.

![screen shot 2015-02-16 at 10 27 10](https://cloud.githubusercontent.com/assets/4811358/6210338/a14767b6-b5c6-11e4-87a5-08458f3a962d.png)

**Comment by masayuki0812** [comment]
let me close at the moment.
