### ISSUE TITLE
bug with timeseries

### ISSUE THREAD

**Issue by tchiloh** [masayuki0812/c3#955]
When the time in timeseries past 00:00 than the chart doesn't go further.

See example in jsfiddle: http://jsfiddle.net/7kYJu/998/

when you remove 00:00 en 01:00 than the chart is good

**Comment by masayuki0812** [comment]
Hi,
This is expected and not a bug because c3 is implemented to sort data based on x when loading. And I think `00:00` and `01:00` are not clear enough to know it's later than `23:00`. So, please try +24h format (e.g. `24:00` http://jsfiddle.net/7kYJu/1102/ ) or add `yyyymmdd` to the xs.
