### ISSUE TITLE
Window can freeze when focused (return from minimize/other tab)

### ISSUE THREAD

**Issue by solgarius** [masayuki0812/c3#956]
I have a chart that is updating every 1-2 seconds, and I've noticed that if the window is minimized/on another tab and the updates continue in the background, when the user comes back to the window, the whole UI freezes up for a period of time (the longer you are away the worse it is), and if the user is away for a few minutes (even 5-10mins), when they come back it can take a minute or so for the UI to become responsive again.

This appears to be something to do with d3.js queueing up transitions because requestAnimationFrame is paused until the window is active again. Then d3 attempts to clear this queue on the next animation frame which just kills the whole UI while it is rendering many transitions. 

If you want an example try it here: http://jsfiddle.net/solgar/phLqwrmb/

I have also raised a bug with d3.js (https://github.com/mbostock/d3/issues/2211) to see if its a problem with the library itself, however I'm only getting this issue on c3.js charts (not custom charts that I've built myself in d3), so I thought I would raise it here because it may be an issue with c3.js.

**Comment by neilwightman** [comment]
I see the exact same problem.

We have graphs which update ever second.  

The best way to reproduce it is to lock the screen when I unlock it (like after lunch) d3.js is reported as being very busy / hung and causes everything to lock up for that tab.  - Linux Mint 17 with Firefox 35

Colleagues see it on mac with chrome too.

**Comment by jmnunezizu** [comment]
I can confirm that this is also happening to me.
I have a dashboard that has some charts and auto-refreshes every 60 seconds. When I go back to the tab it takes a while to become responsive. This is very easy to reproduce when you leave it overnight.

**Comment by igwtsoftware** [comment]
One more confirmation that this is a real issue. Exact same thing is happening to me with the variation that my chrome tab just crashes after a while. My chart updates every 5 seconds. 

Any ideas?

**Comment by neilwightman** [comment]
It may be possible to use : 
https://developers.google.com/chrome/whitepapers/pagevisibility
https://developer.mozilla.org/en-US/docs/Web/Guide/User_experience/Using_the_Page_Visibility_API
to protect updates when the graph isnt visible

There is also https://github.com/serkanyersen/ifvisible.js

**Comment by solgarius** [comment]
@neilwightman, That is essentially the solution I went with to work around this issue. Ultimately it is probably better for my app to do this because it essentially sleeps my app when the user is not actively using the app. I hadn't seen the ifvisible.js module that does it for me though, good tip! 

Also just wondering, in Linux does locking the screen fire the blur event? I noticed in windows with chrome I don't get the blur event when the window is locked. Although that means it also doesn't stop rendering so the issue doesn't happen.

**Comment by masayuki0812** [comment]
It seems not happening in the latest version `0.4.10-rc1` and fixed by this PR https://github.com/masayuki0812/c3/pull/938 .
I'll release `0.4.10` shortly, but it would be nice to test on `0.4.10-rc1` in advance. Thanks.

**Comment by igwtsoftware** [comment]
It seems to fix it partly.
I have a line chart that updates every 1.5 secs. When I change to a different tab and return after 30 seconds or a minute, it still takes a bit for the screen to come back from a blank state. Also, the time it takes to recuperate is related to how long you were on another tab.

Another side issue:
The chart mentioned above is created with 10 initial points, after you come back from another tab, it appends the cached points to my chart. So instead of 10 running points at all times, now I have 20 or 30 and every time I leave the tab it keeps appending.

I am testing with the c3..js for 0.4.10-rc1

**Comment by masayuki0812** [comment]
@igwtsoftware Thanks for testing. How about `0.4.10-rc5`? It looks working well for me. For another side issue, can you open a new issue with the code to reproduce? The last one, it seems fixed already in `0.4.10-rc5`.

**Comment by masayuki0812** [comment]
`0.4.10` has been released, so let me close at the moment. Thanks.
