### ISSUE TITLE
Is there a way to refresh/update the gauge max value?

### ISSUE THREAD

**Issue by jmoller** [masayuki0812/c3#957]
Hello all,

I was looking into the reference guide of c3 but i could not find a way to update/refresh de gauge max value. I need something like this:

gauge.load({
        columns: [['data', 100]],
        max: 30,
    });

gauge.load({
        columns: [['data', 100]],
        max: 20,
    });

The max value in my gauge is dynamic so i need a way to update it.

Thank you!

**Comment by masayuki0812** [comment]
Hi,
Can you try this fiddle? http://jsfiddle.net/7kYJu/1103/
`load` API does not accept `gauge.max` as an argument, but we can change it through `chart.internal.config.gauge_max` variable.

And could you ask this kind of question in Google Group first according to this? https://github.com/masayuki0812/c3#using-the-issue-queue Thanks!

**Comment by masayuki0812** [comment]
Please let me close at this moment.

**Comment by andjimrio** [comment]
It is very interesting for me this feature. Have you in mind to realize it?
