### ISSUE TITLE
c3.generate error catching not working on server

### ISSUE THREAD

**Issue by Salompas** [masayuki0812/c3#960]
Problem: c3.generate is not throwing errors when uploaded to server
JSFiddle: http://jsfiddle.net/xq6wmyvp/10/

Code explanation: the code (in the fiddle) has a function that initializes a chart with a line graph using some data. The path to the data is given as a variable to that function (which is called 'initialize(path)'). This function uses c3.generate to create the graph. If the data is not available or does not exist, c3.generate throws an error (this works locally, but not when uploaded to a server - this is the problem) and the function (initialize) returns false. If the data exists, the graph is loaded and 'initialize' returns true.

Problem Restated: after uploading the code to a server, the function 'initialize(path)' only returns 'true', even if the data is not available/non-existent.

I don't know how to solve this. Can you help me?
Thanks for reading!

**Comment by Salompas** [comment]
Is it possible to add a callback with c3.generate?

**Comment by Salompas** [comment]
(Answer: http://stackoverflow.com/questions/28262940/c3-generate-not-throwing-error)

Under the hood c3 is using a d3.xhr to retrieve the data. This is an async call meaning that it's outside of your try block.

Possible workarounds include:

1. Fix it in the [c3 source code](https://github.com/masayuki0812/c3/blob/master/c3.js#L1903) At line 1903, you see the error is being dropped.

2. Create a [global error handler](http://stackoverflow.com/questions/951791/javascript-global-error-handling/10556743#10556743).

3. Don't use c3's url option. Issue your own [d3 xhr request](https://github.com/mbostock/d3/wiki/Requests) and, if successful, then call c3.generate with the `columns` option. Example below:

```
d3.csv("path/to/file.csv", function(error, json) {
  if (error){
      // handle error properly
      return;
  }
  c3.generate({
    ...
  });
});
```

**Comment by masayuki0812** [comment]
Fixed to throw an error when `data.url` is not found (and get some error in `d3.xhr`). I'll release this in the next version v0.4.11. Thanks!

**Comment by masayuki0812** [comment]
`0.4.10` has been released, so let me close at the moment. Thanks.
