### ISSUE TITLE
Label Overlapping on horizontal bar chart on version v0.4.9

### ISSUE THREAD

**Issue by stanfish** [masayuki0812/c3#961]
See the following fiddles:
using v0.4.9: http://jsfiddle.net/o3r6km35/
using v0.4.8: http://jsfiddle.net/o3r6km35/1/

The label "Users" is overlapping with "ddd" and the text "abcdefgh" got cut off on v0.4.9 
Everything seems fine on v0.4.8

**Comment by propagated** [comment]
I am also experiencing this issue in smaller viewports. Resizing the viewport manually after load appears to 'fix' it.

**Comment by stanfish** [comment]
@propagated , how do you resize the viewport manually?

**Comment by aendrew** [comment]
Marking as bug.

**Comment by propagated** [comment]
@stanfish i mean by physically dragging and resizing a browser window to make it smaller and then larger. I say viewport in the sense of how bootstrap grid determines it. I'm not talented enough to know how to do something like that in code tho.

**Comment by masayuki0812** [comment]
Thanks for reporting. I think this issue has been fixed in `0.4.10-rc2`.

**Comment by stanfish** [comment]
Confirmed that it has been fixed, closing it

**Comment by stanfish** [comment]
Thanks!!
