### ISSUE TITLE
Error installing v0.4.9 via NPM

### ISSUE THREAD

**Issue by gsklee** [masayuki0812/c3#962]
I do not use bower for browser package management but use npm instead. When I do `npm install c3@0.4.9` or `npm install c3@0.4.8` they both will give installation error which I detailed inside brianmcd/contextify#153.

**Comment by gsklee** [comment]
As it was pointed out inside the referenced issue this can be fixed simply by installing g++.

**Comment by luisrudge** [comment]
This is broken in windows. The new version of d3 doesn't [depend on jsdom](https://github.com/mbostock/d3/issues/2190) (the package that is causing the problem). Can we update the d3 dependency?

**Comment by luisrudge** [comment]
any help with that?
