### ISSUE TITLE
X Axis Timezone

### ISSUE THREAD

**Issue by gsklee** [masayuki0812/c3#963]
This example seems to be bugged:

http://c3js.org/samples/axes_x_localtime.html

All ticks are showing `1970-01-01 00:00:02`.

**Comment by masayuki0812** [comment]
Thanks for reporting. It's a bug and will be fixed in the version 0.4.10 (already fixed in master brunch).

**Comment by masayuki0812** [comment]
`0.4.10` has been fixed, so let me close.
