### ISSUE TITLE
Too many entries in the x legend

### ISSUE THREAD

**Issue by dani-h** [masayuki0812/c3#968]
![c3_too_many_entries](https://cloud.githubusercontent.com/assets/5557301/6008504/64faeffc-ab22-11e4-8fae-6cc7b7009b01.png)

Is it possible to reduce the noise of all of these entries and have less entries spread more evenly?

**Comment by masayuki0812** [comment]
I think `axis.x.tick.values` can be used. Can you check this? 
http://c3js.org/samples/axes_x_tick_values.html

And as you can see https://github.com/masayuki0812/c3#using-the-issue-queue , can you ask this kind of question in Google Group? Thanks.

**Comment by masayuki0812** [comment]
Let me close at this moment.
