### ISSUE TITLE
Blank chart in PDF when using wkhtmltopdf

### ISSUE THREAD

**Issue by jkuchta** [masayuki0812/c3#970]
Hi, 

I'm using c3.js (http://c3js.org/) and wkhtmltopdf (http://wkhtmltopdf.org/) to generate a PDF of the HTML page my chart lives on. My chart displays fine in the browser but is blank in wkhtmlpdf. Wkhtmltopdf reports no Javascript errors but the resulting PDF does not include the chart. Does anyone have a work around for this? 

`./wkhtmltopdf --javascript-delay 5000 "http://c3js.org/samples/chart_donut.html" ~/test.pdf `
![test](https://cloud.githubusercontent.com/assets/425863/6014950/e8efa96c-ab2a-11e4-984d-448de71fa3d1.png)

**Comment by masayuki0812** [comment]
Hi, 
Can you ask in Google Group https://groups.google.com/forum/#!forum/c3js ? As you can see here https://github.com/masayuki0812/c3#using-the-issue-queue , Github issues are for bug reports and feature requests only.
