### ISSUE TITLE
Proper way to access d3 scale objects for x/y axes for manual additions?

### ISSUE THREAD

**Issue by jnfeinstein** [masayuki0812/c3#971]
I need to draw some additional elements on a chart, basically some fancy lines and images for various data points.  I couldn't find anything proper in the API, but I did find that I could scale my x and y coordinates (and do everything else related to d3 scales) using `c3chart.internal.x(valueX)` and `c3chart.internal.y(valueY)`, and then draw around those in d3.

Is there anything better?  I assume since I'm accessing `.internal` that this isn't an official part of the API.  I'd be happy to code up some sort of raw d3 or scaling API if other folks think it's worthwhile.

**Comment by masayuki0812** [comment]
Your way is what I intended. `.internal` is not documented yet, but I'm planing to do that and some part of APIs will be moved to `.internal` in the future.

**Comment by masayuki0812** [comment]
Please let me close at the moment.
