### ISSUE TITLE
Allow circles to be turned off at initialisation

### ISSUE THREAD

**Issue by neil-morrison44** [masayuki0812/c3#972]
I'm currently using CSS to hide the data points circles from my line charts, however the code to generate & update the circles is still running.

![screen shot 2015-02-03 at 14 01 02](https://cloud.githubusercontent.com/assets/2095051/6021360/219057da-abad-11e4-9684-63af85b316f6.png)

Here the flow takes 18ms, 2ms of which is updating circles and 5ms of which is redrawing circles.
I modified the redraw call to not include either of the circle functions and didn't notice any side effects.

Also the expandCircles & unexpandCircles calls could be turned off based on the configuration.

**Comment by masayuki0812** [comment]
Yeah, it's true, but I don't think it should be configurable because this is a kind of hack and it's not needed   for ordinary users.
Can you try overwrite internal functions? (e.g. `updateCircles`, `redrawCircles`, etc) Sorry for no documentation, but it's the intended way for advanced user :)

**Comment by masayuki0812** [comment]
let me close at the moment.
