### ISSUE TITLE
Compatibility with D3 3.5.3

### ISSUE THREAD

**Issue by amenadiel** [masayuki0812/c3#976]
I've seen, both in package.json and bower.json, that the dependency on d3.js points to version <= 3.5.0

However, I've also noticed that, in the Gruntfile, the tests are meant to be run using d3 from d3js

```coffee
  jasmine:
    c3:
      src: 'c3.js'
      options:
      specs: 'spec/*-spec.js'
      helpers: 'spec/*-helper.js'
      styles: 'c3.css'
      vendor: 'http://d3js.org/d3.v3.min.js'
```

which means that, at this point, passing the tests means the current c3 version is compatible with d3 3.5.3.

**Comment by masayuki0812** [comment]
You're right. I fixed by this commit and now it's ok. https://github.com/masayuki0812/c3/commit/84d1ac0c
