### ISSUE TITLE
how to flush/resize chart

### ISSUE THREAD

**Issue by udhaya2kmrv** [masayuki0812/c3#977]
I have many chart in my page. Every chart container(div) automatically change based on css property that time chart won't resize. How i flush when chart container width and height changed. for example i have left and right nav panel it is removable one. When i remove my div container resize. n number of chart there how it possible to make resize?

**Comment by JiaJian** [comment]
I think you can create an API method that calls `updateAndRedraw(options)` internally. I do believe `updateAndRedraw(options)` updates the chart size.

**Comment by udhaya2kmrv** [comment]
@JiaJian Please, Can you explain?

**Comment by masayuki0812** [comment]
or call `resize` or `flush` like:
```
var chart = c3.generate({ ... });
chart.resize();
// or chart.flush();
```

Btw, these GitHub issues are for bug reports and feature requests only, so can you ask in Google Group first as you can see here. Thanks.
https://github.com/masayuki0812/c3#using-the-issue-queue

**Comment by masayuki0812** [comment]
Let me close at the moment.
