### ISSUE TITLE
Data labels for multi-series area chart have incorrect position

### ISSUE THREAD

**Issue by rhenna** [masayuki0812/c3#980]
If a chart is configured with more than one area (or area-spline or area-step) series, all but the first series has data labels placed incorrectly. Here's an example: http://jsfiddle.net/fa5t4ba8/ 

When combined with flow, probably because it doesn't redraw the labels, there is an error that appears in the JS log: Uncaught TypeError: Cannot read property 'value' of undefined. Example here: http://jsfiddle.net/Lxxh185v/

**Comment by aendrew** [comment]
Marking as bug, thanks for reporting.

**Comment by masayuki0812** [comment]
Thank you for reporting, but sorry I fixed this issue without your PR - https://github.com/masayuki0812/c3/commit/14db4af699a5442fa170a12e2672bc7275c88392
Now it's ok in `0.4.10-rc3` and I'll release `0.4.10` shortly. Thanks!

**Comment by masayuki0812** [comment]
`0.4.10` has been released, so let me close. Thanks.
