### ISSUE TITLE
timeseries cuts off last date on the x-axis

### ISSUE THREAD

**Issue by Shugardude** [masayuki0812/c3#985]
you can see on the c3 site also.
http://c3js.org/samples/timeseries.html

**Comment by snkashis** [comment]
+1, seeing this behavior too.

**Comment by masayuki0812** [comment]
Please use `padding.right` to set enough value to show it.
I don't think the padding should be calculated by tick text because its position and width will be change according to the data loaded in the chart and the domain currently shown.

**Comment by masayuki0812** [comment]
Let me close at the moment.

**Comment by boatrite** [comment]
Just as a general note to anyone else looking for a solution to this problem:
I couldn't get (forgive the coffeescript) this to work
```
x:
  type: 'timeseries'
  padding:
    right: 6
```
so instead I put the padding on the chart
```
c3.generate
  padding:
    right: 6
```
