### ISSUE TITLE
data.label not rerender when zooming

### ISSUE THREAD

**Issue by rn2dy** [masayuki0812/c3#987]

**Comment by rn2dy** [comment]
Can be verified when adding { labels: true} to the config from this example http://c3js.org/samples/interaction_zoom.html

**Comment by masayuki0812** [comment]
Thanks for reporting. This has been fixed in the latest version v0.4.10-rc4 (I'll release 0.4.10 shortly), so please try this version if possible. Thank you.

**Comment by masayuki0812** [comment]
`0.4.10` has been released, so let me close. Thanks!
