### ISSUE TITLE
data.label not rendering with transition.duration=null

### ISSUE THREAD

**Issue by ryanberckmans** [masayuki0812/c3#988]
data.label not rendering for bar chart with transition.duration = null.

I'm unable to reproduce this in JSFiddle, but I have provided the code which is failing in google-chrome (and phantomjs+princexml): http://jsfiddle.net/8ath969s/1/

Here's generated svg of broken label rendering with bar chart, data.labels=true and transition.duration=null: 

Note the "fill-opacity: 0" and lack of x coordinate.

```html
  <g class="c3-chart-texts"> 
    <g class="c3-chart-text c3-target c3-target-Labelz" style="opacity: 1; pointer-events: none;"> 
      <g class=" c3-texts c3-texts-Labelz"> 
        <text class=" c3-text c3-text-0" text-anchor="middle" style="stroke: none; fill: rgb(31, 119, 180); fill-opacity: 0;">BrokenLabel1</text> 
        <text class=" c3-text c3-text-1" text-anchor="middle" style="stroke: none; fill: rgb(31, 119, 180); fill-opacity: 0;">BrokenLabel2</text> 
      </g> 
    </g> 
  </g> 
```

My current fix is to set transition.duration=1

**Comment by masayuki0812** [comment]
Thanks for reporting, but is this still happening in `v0.4.10-rc4`? I think I don't see it and I'm wondering I fixed in some commits before. Can you see it again? Thanks.

**Comment by ryanberckmans** [comment]
When I get a chance, will try to reproduce with `v0.4.10-rc4` (or whatever latest version is when I get to this.)

**Comment by masayuki0812** [comment]
`0.4.10`has been released, so let me close at the moment. Thanks.
