### ISSUE TITLE
Data.Regions not respecting category axis

### ISSUE THREAD

**Issue by AgentShark** [masayuki0812/c3#989]
In the example below, the dashed region line always renders a line axis type and does not respect the category type.

```
var chart = c3.generate({
    data: {
        columns: [
            ['data1', 60, 110, 260],
            ['data2', 50, 100, 250]
        ],
        regions: {
            data2:[{start:1,'style':'dashed'}]
        }
    },
    axis: {
        x: {
           type: 'category'
        }
    }
});
```

**Comment by masayuki0812** [comment]
Thank you for reporting. I think this has been fixed by the commit above. I'll release this fix in the next version v0.4.10 shortly. Thanks.

**Comment by masayuki0812** [comment]
`0.4.10` has been released, so let me close at the moment. Thanks.

**Comment by pistou** [comment]
It's been 5 years and it's still an issue.
