### ISSUE TITLE
Hover tooltip not showing on data that's been loaded in via .flow

### ISSUE THREAD

**Issue by neil-morrison44** [masayuki0812/c3#991]
The data that's been loaded in via a `.flow()` call doesn't show the tooltip when hovered over until the axis has been updated.

**Comment by masayuki0812** [comment]
Yeah, it's intended, so let me close at the moment.

**Comment by neil-morrison44** [comment]
Why would this be intended behaviour?

Surely you'd expect all data visible on the chart to behave in the same manner regardless of what method used t load it into the chart?

**Comment by masayuki0812** [comment]
Because the position of the cursor is not the position where the tooltip is to be shown anymore while flowing. However, you can change this behavior as you want by modifying the code.

**Comment by neil-morrison44** [comment]
I'm running flows with a duration of 0, I think it'd make sense if the tooltip showed on hover after the data had settled?
Otherwise you end up with the chart having an arbitrary cut off point where the tooltip stops working.
It does make sense why the tooltip wouldn't show while the flow is happening though.

(I'm using flow for performance, although I'm not sure if .load would be just as performant?)

**Comment by anwar6953** [comment]
I have a flow of duration 1000ms. While flowing, it makes sense not to support tooltip on hover.
However, once the flow is complete, the new points should then be hoverable.
