### ISSUE TITLE
Y axis ticks cutoff and possible solution

### ISSUE THREAD

**Issue by ttamminen** [masayuki0812/c3#994]
Hi!

There seems to be many tickets opened regarding the Y axis ticks being cutoff (https://github.com/masayuki0812/c3/issues/982 and https://github.com/masayuki0812/c3/issues/974).

I think I have found reason for that, but I am not 100% sure is my fix correct.

The problem seems to be in this code block:

    $$.d3.select(this).selectAll('text tspan').each(function () {
        var box = this.getBoundingClientRect();
        if (box.left >= 0 && maxWidth < box.width) { maxWidth = box.width; }
    });

The idea seems to be looping all the Y axis tick texts and get the maxWidth. The problem is that if-statement is checking the box.left which at least on a mobile device seems to be negative number. Why is it checking the box.left? Should it be box.width?

Here is a screenshot about the problem. Just open the c3-website and in Google Chrome open Emulator. 
![mobile_yaxis_cutoff](https://cloud.githubusercontent.com/assets/1038081/6163279/9b900d2c-b298-11e4-8341-430dac5f2f53.PNG)

**Comment by masayuki0812** [comment]
Thanks for reporting. Can you try `v0.4.10-rc4`? I think this issue has been fixed in this version.

**Comment by masayuki0812** [comment]
`0.4.10` has been released, so let me close at the moment. Thanks!

**Comment by ttamminen** [comment]
You're absolutely right. Version 0.4.10 fixes this issue! Thank you!
