### ISSUE TITLE
Chart does not render on iOS, only appears when rotating display.

### ISSUE THREAD

**Issue by DanielApt** [masayuki0812/c3#996]
The related JSFiddle can be found here: http://jsfiddle.net/DanielApt/L3a9zksv/

The chart will be blank, however you do still see the axes:
![img_0002](https://cloud.githubusercontent.com/assets/52545/6187313/f47edc44-b37c-11e4-97aa-0a8953b20339.PNG)

After rotating the device, it will display the charts.
![img_0003](https://cloud.githubusercontent.com/assets/52545/6187314/f48478c0-b37c-11e4-804c-04df2fb0e3b8.PNG)

This happens both on Safari and Chrome on iOS8.

I want to also mention tha `alert` causes this, however we've seen this happen in our product which does not use `alert` at all.

PS: If you want to easily open a jsfiddle on a remote device, [this is a useful resource](http://blog.jsfiddle.net/doc-testing-on-mobile).

**Comment by duncanwerner** [comment]
I just ran into the same problem (and updated to make sure I'm on current).  Note that this does /not/ happen for bar or donut charts, only line charts.

I will poke through the code when I have a moment and see if I can find the problem, but for now a workaround is to just call resize() on the chart.

**Comment by pehrlich** [comment]
I've noticed this happen in another case as well:

When on the examples page on Chrome, Safari, or Firefox on OSX Yosemite (the only OS tested by me).  Open multiple examples in new tabs in the background.  You should see that the first couple tabs with line charts will render correctly, while tabs after that will not have any data visualized. Reloading the page while active resolves this.

**Comment by DanielApt** [comment]
Thanks @duncanwerner, at least that's a workaround for now, however it would be nice if we could figure out what is causing it.

**Comment by aendrew** [comment]
@pehrlich I think that's been solved with #938, which is due to requestAnimationFrame not working on inactive tabs. Not sure if this issue is related to that.

**Comment by masayuki0812** [comment]
Is this still happening in the version `v0.4.10-rc4`? I think this had been fixed by this commit: 
https://github.com/masayuki0812/c3/commit/9476cfe510b150e297c609583e21bb351763e205 Can you try this version?

Btw, I'm seeing the samples on iOS Safari, but I don't see this issue.

**Comment by masayuki0812** [comment]
maybe #975 is related

**Comment by DanielApt** [comment]
Don't have an iPad until I'm back in the office on Monday. Will notify you once I know more.

**Comment by masayuki0812** [comment]
`0.4.10` has been released, so let me close at the moment. Please let me know if you still have this issue. Thanks.

**Comment by DanielApt** [comment]
Apologies for the late reply @masayuki0812: yes it works now!
