### ISSUE TITLE
Subtitle in Donut Chart and Hover Action 

### ISSUE THREAD

**Issue by jmoller** [masayuki0812/c3#998]
Hello,

1) Is there any way to add a subtitle below the donut title? If so could you please advise on how to add it?

2) On the hover action in the donut chart, is it posible to display the actual number from the donut portion instead of the percentage?.

Thank you,

**Comment by masayuki0812** [comment]
These GitHub issues are for bug reports and feature requests only, so please use Google Group https://groups.google.com/forum/#!forum/c3js for help.
